# Generated by Django 5.1.14 on 2026-04-08 15:37

import django.db.models.deletion
import modelcluster.fields
import wagtail_color_panel.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('georivacore', '0002_initial'),
        ('home', '0002_create_homepage'),
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='featured_heading',
            field=models.CharField(default='Featured Datasets', max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_background_image',
            field=models.ForeignKey(blank=True, help_text='Satellite or weather imagery used as the hero background. Recommended: 1920×1080px minimum, JPEG. If not set, a built-in fallback gradient is used.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_heading',
            field=models.CharField(default='GeoRiva', max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_show_search',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_subheading',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='homepage',
            name='stats_custom_label',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='homepage',
            name='stats_custom_value',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='homepage',
            name='stats_show_catalog_count',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='stats_show_collection_count',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='stats_show_last_updated',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='FeaturedCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('override_description', models.TextField(blank=True)),
                ('catalog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='georivacore.catalog')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='featured_catalogs', to='home.homepage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GeoRivaSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='GeoRiva', help_text='The name of your GeoRiva instance', max_length=255)),
                ('site_tagline', models.CharField(blank=True, help_text='A short description or tagline for your GeoRiva instance', max_length=500)),
                ('org_name', models.CharField(blank=True, help_text='Name of your organization', max_length=255, verbose_name='Organization Name')),
                ('org_website', models.URLField(blank=True, help_text="URL to your organization's website", verbose_name='Organization Website')),
                ('accent_color', wagtail_color_panel.fields.ColorField(default='#00c9b1', help_text='Hex code for the accent color (e.g., #00c9b1)', max_length=7)),
                ('map_viewer_url', models.CharField(default='/map/', help_text='URL to the map viewer (e.g., /map/)', max_length=200)),
                ('stac_browser_url', models.CharField(default='/stac-browser/', help_text='URL to the STAC browser (e.g., /stac-browser/)', max_length=200)),
                ('org_logo', models.ForeignKey(blank=True, help_text='Logo for your organization (recommended size: 200x50px)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Organization Logo')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'verbose_name': 'GeoRiva Settings',
                'verbose_name_plural': 'GeoRiva Settings',
            },
        ),
    ]
