# Generated by Django 5.2.12 on 2026-03-11 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homepage_featured_heading_and_more'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='georivasettings',
            name='org_logo',
            field=models.ForeignKey(blank=True, help_text='Logo for your organization (recommended size: 200x50px)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Organization Logo'),
        ),
        migrations.AlterField(
            model_name='georivasettings',
            name='org_name',
            field=models.CharField(blank=True, help_text='Name of your organization', max_length=255, verbose_name='Organization Name'),
        ),
        migrations.AlterField(
            model_name='georivasettings',
            name='org_website',
            field=models.URLField(blank=True, help_text="URL to your organization's website", verbose_name='Organization Website'),
        ),
    ]
