services:
  georiva:
    build:
      target: dev
    command: django-dev-no-attach
    environment:
      DEBUG: "True"
      MIGRATE_ON_STARTUP: "true"
      COLLECT_STATICFILES_ON_STARTUP: "true"
    volumes:
      - ./georiva:/georiva/app
    ports:
      - "8000:8000"

  georiva-celery-default-worker:
    build:
      target: dev
    command: celery-default-worker-dev
    environment:
      DEBUG: "True"
    volumes:
      - ./georiva:/georiva/app

  georiva-celery-ingestion-worker:
    build:
      target: dev
    command: celery-ingestion-worker-dev
    environment:
      DEBUG: "True"
    volumes:
      - ./georiva:/georiva/app

  georiva-celery-beat:
    build:
      target: dev
    environment:
      DEBUG: "True"
    volumes:
      - ./georiva:/georiva/app

  georiva-minio:
    ports:
      - "9000:9000"   # S3 API
      - "9001:9001"   # Web Console

  georiva-titiler-app:
    command: [ "python", "-m", "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload" ]
    volumes:
      - ./titiler-app/app:/app/app
    ports:
      - "8888:8000"
    environment:
      - UVICORN_LOG_LEVEL=debug