# Generated by Django 6.0.6 on 2026-06-15 10:02

import django.db.models.deletion
import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('georivacore', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VirtualZarrManifest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('manifest_path', models.CharField(blank=True, help_text='MinIO key for the kerchunk JSON, relative to the georiva-assets bucket. e.g. __manifests__/chirps/chirps-monthly/precipitation.json', max_length=500)),
                ('time_start', models.DateTimeField(blank=True, editable=False, null=True)),
                ('time_end', models.DateTimeField(blank=True, editable=False, null=True)),
                ('item_count', models.PositiveIntegerField(default=0, editable=False)),
                ('status', models.CharField(choices=[('pending', 'Pending build'), ('building', 'Building'), ('ready', 'Ready'), ('stale', 'Stale'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('built_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('locked_by', models.CharField(blank=True, default='', max_length=100)),
                ('error', models.TextField(blank=True)),
                ('variable', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='virtual_zarr_manifest', to='georivacore.variable')),
            ],
            options={
                'ordering': ['variable__collection', 'variable__slug'],
                'indexes': [models.Index(fields=['status'], name='idx_vzm_status')],
            },
        ),
    ]
