# Generated by Django 6.0.6 on 2026-08-10 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('georivavirtualzarr', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='virtualzarrmanifest',
            name='manifest_path',
        ),
        migrations.AddField(
            model_name='virtualzarrmanifest',
            name='repo_path',
            field=models.CharField(blank=True, help_text='Icechunk repository prefix on the zarr bucket, org slug first. e.g. kenya/chirps/chirps-monthly/precipitation/', max_length=500),
        ),
        migrations.AddField(
            model_name='virtualzarrmanifest',
            name='snapshot_id',
            field=models.CharField(blank=True, default='', editable=False, help_text='Icechunk snapshot id of the last successful commit.', max_length=100),
        ),
        migrations.AddField(
            model_name='virtualzarrmanifest',
            name='watermark',
            field=models.DateTimeField(blank=True, editable=False, help_text='Max Asset.modified at the last successful commit.', null=True),
        ),
    ]
