# Generated by Django 6.0.6 on 2026-08-10 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('georivavirtualzarr', '0003_flip_pending_for_icechunk_rebuild'),
    ]

    operations = [
        migrations.AddField(
            model_name='virtualzarrmanifest',
            name='repo_object_count',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='Object count under the repo prefix at the last refresh.'),
        ),
        migrations.AddField(
            model_name='virtualzarrmanifest',
            name='repo_size_bytes',
            field=models.BigIntegerField(default=0, editable=False, help_text='Total bytes under the repo prefix at the last refresh.'),
        ),
        migrations.CreateModel(
            name='VirtualZarrBuildLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('build', 'Build'), ('gc', 'Garbage collection')], max_length=10)),
                ('outcome', models.CharField(choices=[('success', 'Success'), ('failure', 'Failure')], max_length=10)),
                ('mode', models.CharField(blank=True, choices=[('rebuild', 'Rebuild'), ('append', 'Append'), ('up_to_date', 'Up to date')], default='', max_length=20)),
                ('started_at', models.DateTimeField()),
                ('finished_at', models.DateTimeField()),
                ('items_written', models.PositiveIntegerField(default=0)),
                ('items_skipped', models.PositiveIntegerField(default=0, help_text='Items skipped for missing COG asset.')),
                ('error', models.TextField(blank=True)),
                ('snapshot_id', models.CharField(blank=True, default='', help_text='Icechunk snapshot id the build resulted in, if any.', max_length=100)),
                ('manifest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='build_logs', to='georivavirtualzarr.virtualzarrmanifest')),
            ],
            options={
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['started_at'], name='idx_vzbl_started_at')],
            },
        ),
    ]
