# Generated by Django 6.0.6 on 2026-08-10 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('georivavirtualzarr', '0004_virtualzarrmanifest_repo_object_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='virtualzarrbuildlog',
            name='mode',
            field=models.CharField(blank=True, choices=[('rebuild', 'Rebuild'), ('append', 'Append'), ('up_to_date', 'Up to date'), ('no_data', 'No data')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='virtualzarrmanifest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending build'), ('building', 'Building'), ('ready', 'Ready'), ('stale', 'Stale'), ('failed', 'Failed'), ('no_data', 'No data')], db_index=True, default='pending', max_length=20),
        ),
    ]
