"""
Derived health state for DataFeeds.

The `Health` enum is the single source of truth: it carries the sort rank and the
display attributes for each state, *and* the condition that selects it. The SQL
`Case/When` used for ordering is generated by iterating the enum, so the ladder
the database sorts by and the chip the template renders can never disagree.

Declaration order is evaluation order. `rank` is the sort key — the two differ
deliberately (INACTIVE evaluates first but sorts last).
"""

from dataclasses import dataclass
from enum import Enum

from django.db.models import (
    Case,
    DurationField,
    ExpressionWrapper,
    F,
    IntegerField,
    Q,
    Value,
    When,
)
from django.db.models.functions import Extract, Greatest, Least, Now
from django.db.models.lookups import GreaterThan
from django.utils.translation import gettext_lazy as _
from polymorphic.managers import PolymorphicManager
from polymorphic.query import PolymorphicQuerySet

#: A feed is overdue once it has gone longer than `interval_minutes * MULTIPLIER`
#: without a run, clamped at both ends. The floor stops very frequent feeds
#: flickering on ordinary scheduler jitter; the ceiling stops a monthly feed
#: hiding a two-month outage behind a plain 2x rule.
STALE_MULTIPLIER = 2
STALE_FLOOR_MINUTES = 30
STALE_CEILING_MINUTES = 48 * 60


def _seconds_since_last_run():
    return Extract(
        ExpressionWrapper(Now() - F("last_run_at"), output_field=DurationField()),
        "epoch",
    )


def _stale_threshold_seconds():
    clamped_minutes = Least(
        Greatest(F("interval_minutes") * STALE_MULTIPLIER, Value(STALE_FLOOR_MINUTES)),
        Value(STALE_CEILING_MINUTES),
    )
    return ExpressionWrapper(clamped_minutes * Value(60), output_field=IntegerField())


def _is_overdue():
    """True once the gap since the last run exceeds this feed's clamped threshold."""
    return GreaterThan(_seconds_since_last_run(), _stale_threshold_seconds())


@dataclass(frozen=True)
class _State:
    rank: int
    label: str
    color: str  # maps to a --w-color-* status token; see template_conventions.md
    icon: str  # must be a registered Wagtail icon name
    condition: Q | None  # None marks the default (fallthrough) state


class Health(Enum):
    """Feed health states, in evaluation order.

    Each condition is written to stand on its own rather than relying on the
    branches above it, so reordering this ladder changes precedence without
    silently changing what any single state *means*.
    """

    INACTIVE = _State(90, _("Inactive"), "grey", "no-view", Q(is_active=False))
    FAILED = _State(10, _("Failed"), "critical", "cross", Q(last_run_status="failed"))
    PARTIAL = _State(20, _("Partial"), "warning", "warning", Q(last_run_status="partial"))
    NEW = _State(80, _("Never run"), "grey", "time", Q(last_run_at__isnull=True))
    # RUNNING precedes STALE: a feed that is already overdue when a run starts
    # should report that recovery is under way, not that it is still waiting.
    RUNNING = _State(
        50, _("Running"), "info", "spinner", Q(last_run_status__in=("queued", "running"))
    )
    STALE = _State(
        30,
        _("Overdue"),
        "warning",
        "time",
        Q(is_active=True, last_run_at__isnull=False) & Q(_is_overdue()),
    )
    OK = _State(70, _("OK"), "positive", "check", None)

    @property
    def rank(self):
        return self.value.rank

    @property
    def label(self):
        return self.value.label

    @property
    def color(self):
        return self.value.color

    @property
    def icon(self):
        return self.value.icon

    @classmethod
    def from_rank(cls, rank):
        """Resolve an annotated `health_rank` back to its state for rendering."""
        try:
            return next(state for state in cls if state.rank == rank)
        except StopIteration:
            raise KeyError(f"No Health state with rank {rank!r}") from None

    @classmethod
    def as_case(cls):
        """Build the health_rank Case/When by iterating the ladder."""
        whens = [
            When(state.value.condition, then=Value(state.rank))
            for state in cls
            if state.value.condition is not None
        ]
        default = next(state for state in cls if state.value.condition is None)
        return Case(*whens, default=Value(default.rank), output_field=IntegerField())


class DataFeedQuerySet(PolymorphicQuerySet):
    def with_health(self):
        """Annotate `health_rank` so health can be ordered, filtered and counted in SQL."""
        return self.annotate(health_rank=Health.as_case())


class DataFeedManager(PolymorphicManager.from_queryset(DataFeedQuerySet)):
    pass
