# Generated by Django 5.1.14 on 2026-01-06 11:37

import django.core.validators
import django.db.models.deletion
import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoaderConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('interval', models.PositiveIntegerField(default=15, help_text='How often to run the loader (in minutes)', validators=[django.core.validators.MaxValueValidator(60), django.core.validators.MinValueValidator(1)], verbose_name='Interval')),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('last_run_status', models.CharField(blank=True, choices=[('success', 'Success'), ('partial', 'Partial Success'), ('failed', 'Failed'), ('running', 'Running')], max_length=50)),
                ('last_run_message', models.TextField(blank=True)),
                ('last_successful_run_at', models.DateTimeField(blank=True, null=True)),
                ('total_runs', models.IntegerField(default=0)),
                ('successful_runs', models.IntegerField(default=0)),
                ('failed_runs', models.IntegerField(default=0)),
                ('total_files_fetched', models.IntegerField(default=0)),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Loader Configuration',
                'verbose_name_plural': 'Loader Configurations',
            },
        ),
        migrations.CreateModel(
            name='FTPLoaderConfig',
            fields=[
                ('loaderconfig_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='georivaloaders.loaderconfig')),
                ('protocol', models.CharField(choices=[('ftp', 'FTP'), ('sftp', 'SFTP'), ('ftps', 'FTPS')], default='ftp', max_length=10)),
                ('host', models.CharField(max_length=255)),
                ('port', models.IntegerField(default=21)),
                ('username', models.CharField(blank=True, max_length=100)),
                ('password', models.CharField(blank=True, help_text='Password (will be encrypted)', max_length=255)),
                ('private_key', models.TextField(blank=True, help_text='SSH private key for SFTP (optional)')),
                ('remote_path', models.CharField(help_text='Remote directory path', max_length=500)),
                ('filename_pattern', models.CharField(default='*', help_text='Filename pattern (glob or regex)', max_length=255)),
                ('use_regex', models.BooleanField(default=False, help_text='Use regex instead of glob for filename matching')),
                ('recursive', models.BooleanField(default=False, help_text='Search subdirectories recursively')),
                ('timeout', models.IntegerField(default=30, help_text='Connection timeout in seconds')),
                ('passive_mode', models.BooleanField(default=True, help_text='Use passive mode for FTP')),
            ],
            options={
                'verbose_name': 'FTP Loader',
                'verbose_name_plural': 'FTP Loaders',
            },
            bases=('georivaloaders.loaderconfig',),
        ),
        migrations.CreateModel(
            name='HTTPLoaderConfig',
            fields=[
                ('loaderconfig_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='georivaloaders.loaderconfig')),
                ('base_url', models.URLField(help_text='Base URL for data downloads')),
                ('url_pattern', models.CharField(blank=True, help_text="URL pattern with placeholders (e.g., '{base_url}/data/{year}/{month}/{day}.nc')", max_length=500)),
                ('auth_type', models.CharField(choices=[('none', 'None'), ('basic', 'Basic Auth'), ('bearer', 'Bearer Token'), ('api_key', 'API Key'), ('custom_header', 'Custom Header')], default='none', max_length=20)),
                ('auth_username', models.CharField(blank=True, max_length=100)),
                ('auth_password', models.CharField(blank=True, max_length=255)),
                ('auth_token', models.CharField(blank=True, help_text='Bearer token or API key', max_length=500)),
                ('auth_header_name', models.CharField(blank=True, default='Authorization', help_text='Custom header name for authentication', max_length=100)),
                ('custom_headers', models.JSONField(blank=True, default=dict, help_text='Additional HTTP headers as JSON object')),
                ('query_params', models.JSONField(blank=True, default=dict, help_text='Query parameters to include in requests')),
                ('timeout', models.IntegerField(default=60)),
                ('max_retries', models.IntegerField(default=3)),
                ('verify_ssl', models.BooleanField(default=True, help_text='Verify SSL certificates')),
            ],
            options={
                'verbose_name': 'HTTP Loader',
                'verbose_name_plural': 'HTTP Loaders',
            },
            bases=('georivaloaders.loaderconfig',),
        ),
        migrations.CreateModel(
            name='S3LoaderConfig',
            fields=[
                ('loaderconfig_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='georivaloaders.loaderconfig')),
                ('bucket_name', models.CharField(max_length=255)),
                ('prefix', models.CharField(blank=True, help_text='S3 prefix (folder path)', max_length=500)),
                ('endpoint_url', models.URLField(blank=True, help_text='Custom endpoint URL (leave blank for AWS S3)')),
                ('region', models.CharField(default='us-east-1', max_length=50)),
                ('access_key', models.CharField(blank=True, max_length=255)),
                ('secret_key', models.CharField(blank=True, max_length=255)),
                ('filename_pattern', models.CharField(default='*', help_text='Filename pattern (glob)', max_length=255)),
                ('requester_pays', models.BooleanField(default=False, help_text='Enable requester pays for AWS buckets')),
            ],
            options={
                'verbose_name': 'S3 Loader',
                'verbose_name_plural': 'S3 Loaders',
            },
            bases=('georivaloaders.loaderconfig',),
        ),
    ]
