# Generated by Django 5.1.14 on 2026-06-09 10:02

import django.core.validators
import django.db.models.deletion
import django_extensions.db.fields
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('georivacore', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataFeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('interval_minutes', models.PositiveIntegerField(default=360, help_text='Minutes between runs (global default for all collections)', validators=[django.core.validators.MinValueValidator(5)], verbose_name='Run Interval')),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('last_run_status', models.CharField(blank=True, choices=[('success', 'Success'), ('partial', 'Partial'), ('failed', 'Failed'), ('queued', 'Queued'), ('running', 'Running'), ('empty', 'No Data')], max_length=20)),
                ('last_run_message', models.TextField(blank=True)),
                ('last_success_at', models.DateTimeField(blank=True, null=True)),
                ('total_runs', models.PositiveIntegerField(default=0)),
                ('total_files_fetched', models.PositiveIntegerField(default=0)),
                ('total_bytes_transferred', models.BigIntegerField(default=0)),
                ('catalog', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='data_feed', to='georivacore.catalog', verbose_name='Catalog')),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Data Feed',
                'verbose_name_plural': 'Data Feeds',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DataFeedCollectionLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('definition_key', models.CharField(blank=True, help_text='The CollectionDefinition.key used to provision this link.', max_length=100)),
                ('interval_minutes', models.PositiveIntegerField(blank=True, help_text="Minutes between runs for this collection. Leave blank to use the feed's global interval.", null=True, validators=[django.core.validators.MinValueValidator(5)], verbose_name='Collection Run Interval')),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feed_links', to='georivacore.collection')),
                ('data_feed', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_links', to='georivasources.datafeed')),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['id'],
                'unique_together': {('data_feed', 'collection')},
            },
        ),
    ]
