# Generated by Django 5.1.14 on 2026-04-08 15:37

import django.core.validators
import django.db.models.deletion
import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('georivacore', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoaderProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('interval_minutes', models.PositiveIntegerField(default=360, help_text='Minutes between runs', validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(1440)], verbose_name='Run Interval')),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('last_run_status', models.CharField(blank=True, choices=[('success', 'Success'), ('partial', 'Partial'), ('failed', 'Failed'), ('queued', 'Queued'), ('running', 'Running'), ('empty', 'No Data')], max_length=20)),
                ('last_run_message', models.TextField(blank=True)),
                ('last_success_at', models.DateTimeField(blank=True, null=True)),
                ('total_runs', models.PositiveIntegerField(default=0)),
                ('total_files_fetched', models.PositiveIntegerField(default=0)),
                ('total_bytes_transferred', models.BigIntegerField(default=0)),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Loader Profile',
                'verbose_name_plural': 'Loader Profiles',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LoaderRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('started_at', models.DateTimeField()),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('running', 'Running'), ('success', 'Success'), ('partial', 'Partial'), ('failed', 'Failed'), ('empty', 'Empty'), ('queued', 'Queued')], default='running', max_length=20)),
                ('files_requested', models.IntegerField(default=0)),
                ('files_fetched', models.IntegerField(default=0)),
                ('files_skipped', models.IntegerField(default=0)),
                ('files_failed', models.IntegerField(default=0)),
                ('files_queued', models.IntegerField(default=0)),
                ('bytes_transferred', models.BigIntegerField(default=0)),
                ('run_time', models.DateTimeField(blank=True, null=True)),
                ('errors', models.JSONField(blank=True, default=list)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loader_runs', to='georivacore.collection')),
                ('loader_profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='runs', to='georivasources.loaderprofile')),
            ],
            options={
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['collection', '-started_at'], name='georivasour_collect_839595_idx'), models.Index(fields=['status'], name='georivasour_status_4b6050_idx')],
            },
        ),
    ]
