# Generated by Django 5.1.14 on 2026-01-30 09:14

import django.core.validators
import django.db.models.deletion
import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoaderProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('data_source_type', models.CharField(max_length=100, verbose_name='Data Source')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('interval_minutes', models.PositiveIntegerField(default=360, help_text='Minutes between runs', validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(1440)], verbose_name='Run Interval')),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('last_run_status', models.CharField(blank=True, choices=[('success', 'Success'), ('partial', 'Partial'), ('failed', 'Failed'), ('queued', 'Queued'), ('running', 'Running'), ('empty', 'No Data')], max_length=20)),
                ('last_run_message', models.TextField(blank=True)),
                ('last_success_at', models.DateTimeField(blank=True, null=True)),
                ('total_runs', models.PositiveIntegerField(default=0)),
                ('total_files_fetched', models.PositiveIntegerField(default=0)),
                ('total_bytes_transferred', models.BigIntegerField(default=0)),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Loader Profile',
                'verbose_name_plural': 'Loader Profiles',
                'ordering': ['name'],
            },
        ),
    ]
