# Generated by Django 5.1.14 on 2026-06-08 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('georivasources', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DataFeedJob',
        ),
    ]
