# Generated by Django 5.2.15 on 2026-06-12 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('georivasources', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FetchRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='running', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('files_requested', models.IntegerField(default=0)),
                ('files_fetched', models.IntegerField(default=0)),
                ('files_skipped', models.IntegerField(default=0)),
                ('files_failed', models.IntegerField(default=0)),
                ('bytes_transferred', models.BigIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('data_feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fetch_runs', to='georivasources.datafeed')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='FetchedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(max_length=500)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('fetching', 'Fetching'), ('stored', 'Stored'), ('skipped', 'Skipped'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('skip_reason', models.CharField(blank=True, max_length=255)),
                ('error', models.TextField(blank=True)),
                ('bytes_transferred', models.BigIntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('fetch_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fetched_files', to='georivasources.fetchrun')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
