# Generated by Django 5.1.14 on 2026-02-18 11:05

import django.db.models.deletion
import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('georivacore', '0004_remove_catalog_loader_profile_and_more'),
        ('georivasources', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoaderRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('started_at', models.DateTimeField()),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('running', 'Running'), ('success', 'Success'), ('partial', 'Partial'), ('failed', 'Failed'), ('empty', 'Empty'), ('queued', 'Queued')], default='running', max_length=20)),
                ('files_requested', models.IntegerField(default=0)),
                ('files_fetched', models.IntegerField(default=0)),
                ('files_skipped', models.IntegerField(default=0)),
                ('files_failed', models.IntegerField(default=0)),
                ('files_queued', models.IntegerField(default=0)),
                ('bytes_transferred', models.BigIntegerField(default=0)),
                ('run_time', models.DateTimeField(blank=True, null=True)),
                ('errors', models.JSONField(blank=True, default=list)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loader_runs', to='georivacore.collection')),
            ],
            options={
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['collection', '-started_at'], name='georivasour_collect_839595_idx'), models.Index(fields=['status'], name='georivasour_status_4b6050_idx')],
            },
        ),
    ]
