# Generated by Django 5.1.14 on 2026-05-28 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('georivacore', '0005_collection_boundary_stats_levels'),
        ('georivasources', '0001_initial'),
        ('task_ferry', '0002_add_ingestion_job'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoaderJob',
            fields=[
                ('job_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='task_ferry.job')),
                ('files_total', models.IntegerField(default=0)),
                ('files_fetched', models.IntegerField(default=0)),
                ('files_skipped', models.IntegerField(default=0)),
                ('files_failed', models.IntegerField(default=0)),
                ('bytes_transferred', models.BigIntegerField(default=0)),
                ('collection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loader_jobs', to='georivacore.collection')),
                ('loader_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='georivasources.loaderprofile')),
            ],
            bases=('task_ferry.job',),
        ),
    ]
