# Generated by Django 6.0.6 on 2026-06-22 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('georivasources', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datafeed',
            name='target_tier',
            field=models.CharField(choices=[('published', 'Published (serve directly)'), ('staging', 'Staging (hold for derivation)')], default='published', help_text='Published: fetched files are materialized into served layers. Staging: fetched files are held as raw inputs for derivation and are not served or auto-materialized.', max_length=20, verbose_name='Target Tier'),
        ),
    ]
