# Generated by Django 5.2.11 on 2026-02-18 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('georivasources', '0002_loaderrun'),
    ]

    operations = [
        migrations.AddField(
            model_name='loaderrun',
            name='loader_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='runs', to='georivasources.loaderprofile'),
        ),
    ]
