# Generated by Django 6.0.6 on 2026-06-25 08:36

import django.core.validators
import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('georivasources', '0002_datafeed_target_tier'),
    ]

    operations = [
        migrations.CreateModel(
            name='DerivedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('definition_key', models.CharField(help_text='The DerivedProductDefinition.key this config was provisioned from.', max_length=100)),
                ('recipe_type', models.CharField(help_text='The registered recipe this product runs.', max_length=100)),
                ('config', models.JSONField(blank=True, default=dict, help_text="Operator options, validated against the definition's config_schema.")),
                ('is_enabled', models.BooleanField(default=True, help_text='Disable to pause this product without deleting its configuration.')),
                ('interval_minutes', models.PositiveIntegerField(blank=True, help_text='Minutes between runs for a scheduled product. Ignored for event/manual products.', null=True, validators=[django.core.validators.MinValueValidator(5)], verbose_name='Run Interval')),
                ('data_feed', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='derived_products', to='georivasources.datafeed')),
            ],
            options={
                'ordering': ['id'],
                'unique_together': {('data_feed', 'definition_key')},
            },
        ),
    ]
