# Generated by Django 6.0.6 on 2026-06-25 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('georivasources', '0003_derivedproduct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datafeed',
            name='target_tier',
        ),
    ]
