# Generated by Django 5.2.11 on 2026-03-09 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('georivasources', '0003_loaderrun_loader_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loaderprofile',
            name='data_source_type',
        ),
    ]
