# Generated by Django 6.0.6 on 2026-06-25 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('georivasources', '0004_remove_datafeed_target_tier'),
    ]

    operations = [
        migrations.AddField(
            model_name='derivedproduct',
            name='last_run_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
