# Generated by Django 6.0.6 on 2026-07-06 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('georivasources', '0005_derivedproduct_last_run_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='derivedproduct',
            name='description',
            field=models.TextField(blank=True, help_text='Optional display description. Leave blank to use the declared one.'),
        ),
        migrations.AddField(
            model_name='derivedproduct',
            name='title',
            field=models.CharField(blank=True, help_text='Optional display name. Leave blank to use the declared label.', max_length=255),
        ),
    ]
