# Generated by Django 6.0.6 on 2026-07-07 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('georivacore', '0005_collection_visibility'),
        ('georivasources', '0006_derivedproduct_description_derivedproduct_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='DerivedProductInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=100)),
                ('tier', models.CharField(max_length=20)),
                ('required', models.BooleanField(default=True)),
                ('source_key', models.CharField(help_text='The declared collection key this binding resolved from.', max_length=100)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='derived_product_inputs', to='georivacore.collection')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='input_bindings', to='georivasources.derivedproduct')),
            ],
            options={
                'ordering': ['id'],
                'unique_together': {('product', 'role')},
            },
        ),
        migrations.CreateModel(
            name='DerivedProductOutput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=100)),
                ('output_key', models.CharField(help_text='The declared output collection key this binding resolved from.', max_length=100)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='derived_product_outputs', to='georivacore.collection')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='output_bindings', to='georivasources.derivedproduct')),
            ],
            options={
                'ordering': ['id'],
                'unique_together': {('product', 'role')},
            },
        ),
    ]
