# Generated by Django 6.0.6 on 2026-07-14 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('georivasources', '0008_backfill_product_bindings'),
    ]

    operations = [
        migrations.AddField(
            model_name='fetchedfile',
            name='request_payload',
            field=models.JSONField(blank=True, help_text='Serialized FileRequest that produced this file, enabling per-file re-fetch. Null on records that predate the feature.', null=True),
        ),
    ]
