# Generated by Django 6.0.6 on 2026-08-06 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('georivasources', '0009_fetchedfile_request_payload'),
    ]

    operations = [
        migrations.AddField(
            model_name='fetchrun',
            name='resumed_from',
            field=models.ForeignKey(blank=True, help_text='The interrupted run this run was auto-enqueued to resume. Chain depth bounds the auto-resume cap.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resumes', to='georivasources.fetchrun'),
        ),
        migrations.AlterField(
            model_name='fetchrun',
            name='status',
            field=models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('interrupted', 'Interrupted')], default='running', max_length=20),
        ),
    ]
