# Generated by Django 5.1.14 on 2026-01-28 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('georivasources', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ECMWFAIFSLoaderProfile',
            fields=[
                ('loaderprofile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='georivasources.loaderprofile')),
            ],
            options={
                'verbose_name': 'ECMWF AIFS Loader Profile',
                'verbose_name_plural': 'ECMWF AIFS Loader Profiles',
            },
            bases=('georivasources.loaderprofile', models.Model),
        ),
    ]
