# Generated by Django 5.1.14 on 2026-01-30 10:59

import django.core.validators
import django_better_admin_arrayfield.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecmwf_aifs_source', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ecmwfaifsloaderprofile',
            options={'verbose_name': 'ECMWF AIFS Loader Profile'},
        ),
        migrations.AddField(
            model_name='ecmwfaifsloaderprofile',
            name='display_timezone',
            field=models.CharField(default='Africa/Nairobi', max_length=64),
        ),
        migrations.AddField(
            model_name='ecmwfaifsloaderprofile',
            name='end_day',
            field=models.IntegerField(default=5, help_text='Forecast end day (max 15)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(15)]),
        ),
        migrations.AddField(
            model_name='ecmwfaifsloaderprofile',
            name='run_hours',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.IntegerField(choices=[(0, '00Z'), (6, '06Z'), (12, '12Z'), (18, '18Z')]), blank=True, default=list, help_text='Which model runs to fetch from (e.g., 00Z and 12Z are most common)', null=True, size=None),
        ),
        migrations.AddField(
            model_name='ecmwfaifsloaderprofile',
            name='start_day',
            field=models.IntegerField(default=0, help_text='Forecast start day (0 = analysis time)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(15)]),
        ),
    ]
