# Generated by Django 5.1.14 on 2026-01-30 16:12

import django_better_admin_arrayfield.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecmwf_aifs_source', '0002_alter_ecmwfaifsloaderprofile_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecmwfaifsloaderprofile',
            name='run_hours',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.IntegerField(choices=[(0, '00Z'), (6, '06Z'), (12, '12Z'), (18, '18Z')]), blank=True, default=[0, 12], help_text='Which model runs to fetch from (e.g., 00Z and 12Z are most common)', null=True, size=None),
        ),
    ]
