# Generated by Django 6.0.6 on 2026-07-27 09:53

import django.db.models.deletion
import django_countries.fields
import georiva.organisations.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Display name of the institution.', max_length=255)),
                ('slug', models.SlugField(help_text="Immutable. Used as the organisation's subdomain and as the first segment of every storage path. Cannot be changed after creation.", unique=True, validators=[georiva.organisations.validators.validate_org_slug])),
                ('description', models.TextField(blank=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True)),
                ('country', django_countries.fields.CountryField(blank=True, help_text='ISO 3166-1 alpha-2. Blank for regional or continental centres.', max_length=2)),
                ('default_provider', models.CharField(blank=True, help_text='Prefills the provider name on new catalogs. Catalog-level values win.', max_length=255)),
                ('default_provider_url', models.URLField(blank=True, help_text='Prefills the provider URL on new catalogs. Catalog-level values win.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('site', models.OneToOneField(help_text='The Wagtail Site this organisation is served from.', on_delete=django.db.models.deletion.PROTECT, related_name='organisation', to='wagtailcore.site')),
            ],
            options={
                'verbose_name': 'Organisation',
                'verbose_name_plural': 'Organisations',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OrganisationMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Org Admin'), ('member', 'Member')], default='member', max_length=16)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='organisations.organisation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organisation_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Organisation membership',
                'verbose_name_plural': 'Organisation memberships',
                'ordering': ['organisation__name'],
                'unique_together': {('user', 'organisation')},
            },
        ),
    ]
