# Generated by Django 5.2.13 on 2026-04-20 15:00

import django.db.models.deletion
import django_extensions.db.fields
import timescale.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adminboundarymanager', '0007_boundarymenupermission'),
        ('georivacore', '0005_collection_boundary_stats_levels'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoundaryZonalStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('time', timescale.db.models.fields.TimescaleDateTimeField(interval='1 day')),
                ('mean', models.FloatField(blank=True, null=True)),
                ('min', models.FloatField(blank=True, null=True)),
                ('max', models.FloatField(blank=True, null=True)),
                ('sum', models.FloatField(blank=True, null=True)),
                ('std', models.FloatField(blank=True, null=True)),
                ('count', models.IntegerField(blank=True, help_text='Number of valid (non-NaN) pixels within the boundary.', null=True)),
                ('boundary', models.ForeignKey(help_text='Administrative boundary region.', on_delete=django.db.models.deletion.CASCADE, related_name='zonal_stats', to='adminboundarymanager.adminboundary')),
                ('item', models.ForeignKey(db_constraint=False, help_text='Source item (carries valid_time and reference_time).', on_delete=django.db.models.deletion.CASCADE, related_name='zonal_stats', to='georivacore.item')),
                ('variable', models.ForeignKey(help_text='Variable these stats describe.', on_delete=django.db.models.deletion.CASCADE, related_name='zonal_stats', to='georivacore.variable')),
            ],
            options={
                'ordering': ['-time'],
                'indexes': [models.Index(fields=['boundary', 'variable', 'time'], name='idx_bzs_boundary_variable_time'), models.Index(fields=['boundary', 'variable', 'item'], name='idx_bzs_boundary_variable_item')],
            },
        ),
    ]
