# Generated by Django 5.1.14 on 2026-06-03 09:58

import django.db.models.deletion
import django_extensions.db.fields
import timescale.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adminboundarymanager', '0007_boundarymenupermission'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoundaryZonalStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('time', timescale.db.models.fields.TimescaleDateTimeField(interval='1 day')),
                ('mean', models.FloatField(blank=True, null=True)),
                ('min', models.FloatField(blank=True, null=True)),
                ('max', models.FloatField(blank=True, null=True)),
                ('sum', models.FloatField(blank=True, null=True)),
                ('std', models.FloatField(blank=True, null=True)),
                ('count', models.IntegerField(blank=True, help_text='Number of valid (non-NaN) pixels within the boundary.', null=True)),
                ('boundary', models.ForeignKey(help_text='Administrative boundary region.', on_delete=django.db.models.deletion.CASCADE, related_name='zonal_stats', to='adminboundarymanager.adminboundary')),
            ],
            options={
                'ordering': ['-time'],
            },
        ),
    ]
