# Generated by Django 5.2.13 on 2026-04-20 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminboundarymanager', '0007_boundarymenupermission'),
        ('georiva_analysis_zonal_stats', '0001_initial'),
        ('georivacore', '0005_collection_boundary_stats_levels'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='boundaryzonalstats',
            constraint=models.UniqueConstraint(fields=('time', 'item', 'variable', 'boundary'), name='uq_bzs_time_item_variable_boundary'),
        ),
    ]
