# Generated by Django 5.1.14 on 2026-06-03 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('georiva_analysis_zonal_stats', '0001_initial'),
        ('georivacore', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='boundaryzonalstats',
            name='item',
            field=models.ForeignKey(db_constraint=False, help_text='Source item (carries valid_time and reference_time).', on_delete=django.db.models.deletion.CASCADE, related_name='zonal_stats', to='georivacore.item'),
        ),
        migrations.AddField(
            model_name='boundaryzonalstats',
            name='variable',
            field=models.ForeignKey(help_text='Variable these stats describe.', on_delete=django.db.models.deletion.CASCADE, related_name='zonal_stats', to='georivacore.variable'),
        ),
        migrations.AddIndex(
            model_name='boundaryzonalstats',
            index=models.Index(fields=['boundary', 'variable', 'time'], name='idx_bzs_boundary_variable_time'),
        ),
        migrations.AddIndex(
            model_name='boundaryzonalstats',
            index=models.Index(fields=['boundary', 'variable', 'item'], name='idx_bzs_boundary_variable_item'),
        ),
        migrations.AddConstraint(
            model_name='boundaryzonalstats',
            constraint=models.UniqueConstraint(fields=('time', 'item', 'variable', 'boundary'), name='uq_bzs_time_item_variable_boundary'),
        ),
    ]
