# Generated by Django 6.0.6 on 2026-06-22 15:19

import django.db.models.deletion
import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('georivacore', '0004_alter_asset_format_alter_asset_roles'),
    ]

    operations = [
        migrations.CreateModel(
            name='DerivationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('recipe_type', models.CharField(db_index=True, max_length=100)),
                ('recipe_version', models.CharField(max_length=50)),
                ('unit_key', models.JSONField(default=dict)),
                ('unit_hash', models.CharField(db_index=True, max_length=64)),
                ('input_hash', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('skipped', 'Skipped (idempotent no-op)'), ('not_ready', 'Not ready')], db_index=True, default='pending', max_length=20)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('locked_by', models.CharField(blank=True, max_length=255)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error', models.TextField(blank=True)),
                ('produced_item', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derivation_runs', to='georivacore.item')),
            ],
            options={
                'indexes': [models.Index(fields=['recipe_type', 'status'], name='georivaproc_recipe__8b72b1_idx'), models.Index(fields=['status', 'locked_at'], name='georivaproc_status_8f5dd0_idx')],
                'constraints': [models.UniqueConstraint(fields=('recipe_type', 'unit_hash'), name='unique_run_per_recipe_unit')],
            },
        ),
    ]
