# Generated by Django 6.0.6 on 2026-06-25 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('georivaprocessing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='derivationrun',
            name='origin',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
