# Generated by Django 6.0.6 on 2026-07-09 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('georivaprocessing', '0002_derivationrun_origin'),
    ]

    operations = [
        migrations.AddField(
            model_name='derivationrun',
            name='attempts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='derivationrun',
            name='last_retry_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='derivationrun',
            name='last_retry_reason',
            field=models.CharField(choices=[('initial', 'Initial run'), ('celery_retry', 'Celery auto-retry'), ('stale_running_reclaim', 'Stale RUNNING reclaimed'), ('input_stale', 'Input changed (recompute)'), ('manual_rerun', 'Manual re-run')], default='initial', max_length=32),
        ),
    ]
