# Generated by Django 6.0.6 on 2026-08-06 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('georivaprocessing', '0003_derivationrun_attempts_derivationrun_last_retry_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='derivationrun',
            name='last_retry_reason',
            field=models.CharField(choices=[('initial', 'Initial run'), ('celery_retry', 'Celery auto-retry'), ('stale_running_reclaim', 'Stale RUNNING reclaimed'), ('input_stale', 'Input changed (recompute)'), ('manual_rerun', 'Manual re-run'), ('not_ready_sweep', 'Inputs ready (sweep revival)'), ('input_arrived', 'Required input arrived')], default='initial', max_length=32),
        ),
    ]
