# Generated by Django 5.2.12 on 2026-03-30 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('georivacore', '0011_collection_forecast_horizon_hours_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZarrSyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_path', models.CharField(max_length=500)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('retry_count', models.IntegerField(default=0)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('locked_by', models.CharField(blank=True, default='', max_length=100)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='zarr_sync_logs', to='georivacore.item')),
                ('variable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zarr_sync_logs', to='georivacore.variable')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['store_path', 'status'], name='idx_zarrsync_store_status'), models.Index(fields=['status', 'created_at'], name='idx_zarrsync_status_created')],
                'unique_together': {('item', 'variable')},
            },
        ),
    ]
