# Generated by Django 5.1.14 on 2026-06-08 17:06

import timezone_field.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecmwf_opendata_source', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecmwfaifsdatafeed',
            name='display_timezone',
            field=timezone_field.fields.TimeZoneField(default='Africa/Nairobi'),
        ),
    ]
