# Generated by Django 6.0.6 on 2026-08-03 10:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="What holds this key — 'QGIS on my laptop', 'ingest cron'.", max_length=80)),
                ('prefix', models.CharField(editable=False, help_text='The visible start of the key, so its owner can tell it apart.', max_length=10)),
                ('hashed_key', models.CharField(editable=False, max_length=64, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Optional. After this moment the key stops working.', null=True)),
                ('revoked_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('last_used_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'API key',
                'ordering': ['-created'],
            },
        ),
    ]
