# Generated by Django 5.2.11 on 2026-02-17 10:45

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('georivasources', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CHIRPSLoaderProfile',
            fields=[
                ('loaderprofile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='georivasources.loaderprofile')),
                ('period', models.CharField(choices=[('monthly', 'Monthly'), ('pentadal', 'Pentadal (5-day)')], max_length=10)),
                ('default_start_date', models.DateField(default=datetime.date(1981, 1, 1), help_text='Default backfill start date (if not supplied elsewhere).')),
                ('head_timeout', models.IntegerField(default=20, help_text='HTTP HEAD timeout (seconds) used for existence checks.')),
            ],
            options={
                'verbose_name': 'CHIRPS Loader Profile',
            },
            bases=('georivasources.loaderprofile', models.Model),
        ),
    ]
