# Generated by Django 5.1.14 on 2026-01-06 11:37

import django.contrib.postgres.fields
import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('provider', models.CharField(blank=True, max_length=255)),
                ('provider_url', models.URLField(blank=True)),
                ('license', models.CharField(blank=True, max_length=255)),
                ('file_format', models.CharField(choices=[('grib', 'GRIB/GRIB2'), ('netcdf', 'NetCDF'), ('geotiff', 'GeoTIFF'), ('zarr', 'ZARR')], max_length=20)),
                ('archive_source_files', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Catalogs',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('slug', models.SlugField(max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('bounds', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, null=True, size=4)),
                ('crs', models.CharField(default='EPSG:4326', max_length=50)),
                ('time_resolution', models.CharField(blank=True, choices=[('hourly', 'Hourly'), ('3hourly', '3-Hourly'), ('6hourly', '6-Hourly'), ('daily', 'Daily'), ('dekadal', 'Dekadal'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], max_length=20)),
                ('time_start', models.DateTimeField(blank=True, editable=False, null=True)),
                ('time_end', models.DateTimeField(blank=True, editable=False, null=True)),
                ('item_count', models.PositiveIntegerField(default=0, editable=False)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['catalog', 'sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ColorPalette',
            fields=[
                ('id', models.SlugField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('palette_type', models.CharField(choices=[('sequential', 'Sequential'), ('diverging', 'Diverging'), ('categorical', 'Categorical')], default='sequential', max_length=20)),
                ('colors', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=7), help_text="List of hex colors, e.g., ['#f7fbff', '#08306b']", size=None)),
                ('center_value', models.FloatField(blank=True, help_text='Center value for diverging palettes', null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Variable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('slug', models.SlugField(max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('transform_type', models.CharField(choices=[('passthrough', 'Passthrough (direct read)'), ('unit_convert', 'Unit Conversion'), ('vector_magnitude', 'Vector Magnitude (√(u² + v²))'), ('vector_direction', 'Vector Direction (atan2)'), ('band_math', 'Band Math (expression)'), ('rgb_composite', 'RGB Composite'), ('threshold', 'Threshold (mask)')], default='passthrough', max_length=30)),
                ('transform_expression', models.TextField(blank=True, help_text="For band_math: e.g., '(nir - red) / (nir + red)'")),
                ('unit_conversion', models.CharField(blank=True, choices=[('', 'None'), ('K_to_C', 'Kelvin to Celsius'), ('Pa_to_hPa', 'Pascal to hectoPascal'), ('m_to_mm', 'Meters to Millimeters'), ('ms_to_kmh', 'm/s to km/h'), ('kgm2s_to_mm', 'kg/m²/s to mm')], max_length=50)),
                ('units', models.CharField(blank=True, max_length=50)),
                ('value_min', models.FloatField(blank=True, null=True)),
                ('value_max', models.FloatField(blank=True, null=True)),
                ('scale_type', models.CharField(choices=[('linear', 'Linear'), ('log', 'Logarithmic'), ('sqrt', 'Square Root'), ('diverging', 'Diverging')], default='linear', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VariableSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('source_name', models.CharField(help_text="Name in source file, e.g., 'TMP_2maboveground', 'B04'", max_length=100)),
                ('vertical_dimension', models.CharField(blank=True, max_length=50)),
                ('vertical_value', models.FloatField(blank=True, null=True)),
                ('band_index', models.PositiveIntegerField(blank=True, null=True)),
                ('source_units', models.CharField(blank=True, max_length=50)),
                ('source_dtype', models.CharField(blank=True, max_length=20)),
                ('source_nodata', models.FloatField(blank=True, null=True)),
                ('role', models.CharField(default='primary', max_length=20)),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
