# Generated by Django 5.1.14 on 2026-02-10 12:30

import django.contrib.postgres.fields
import django.db.models.deletion
import django_extensions.db.fields
import timescale.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adminboundarymanager', '0007_boundarymenupermission'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('href', models.CharField(help_text='Storage path or URL', max_length=500)),
                ('media_type', models.CharField(blank=True, help_text='MIME type', max_length=100)),
                ('roles', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('data', 'Data'), ('visual', 'Visual'), ('thumbnail', 'Thumbnail'), ('overview', 'Overview'), ('metadata', 'Metadata')], max_length=20), default=list, size=None)),
                ('format', models.CharField(blank=True, choices=[('cog', 'Cloud-Optimized GeoTIFF'), ('zarr', 'Zarr'), ('geotiff', 'GeoTIFF'), ('png', 'PNG'), ('webp', 'WebP'), ('jpeg', 'JPEG'), ('json', 'JSON')], max_length=20)),
                ('file_size', models.BigIntegerField(blank=True, null=True)),
                ('checksum', models.CharField(blank=True, max_length=64)),
                ('width', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('bands', models.IntegerField(blank=True, default=1, null=True)),
                ('stats_min', models.FloatField(blank=True, null=True)),
                ('stats_max', models.FloatField(blank=True, null=True)),
                ('stats_mean', models.FloatField(blank=True, null=True)),
                ('stats_std', models.FloatField(blank=True, null=True)),
                ('extra_fields', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('slug', models.SlugField(max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('bounds', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, null=True, size=4)),
                ('crs', models.CharField(default='EPSG:4326', max_length=50)),
                ('time_resolution', models.CharField(blank=True, choices=[('hourly', 'Hourly'), ('3hourly', '3-Hourly'), ('6hourly', '6-Hourly'), ('daily', 'Daily'), ('dekadal', 'Dekadal'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], max_length=20)),
                ('time_start', models.DateTimeField(blank=True, editable=False, null=True)),
                ('time_end', models.DateTimeField(blank=True, editable=False, null=True)),
                ('item_count', models.PositiveIntegerField(default=0, editable=False)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['catalog', 'sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ColorPalette',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('palette_type', models.CharField(choices=[('sequential', 'Sequential'), ('diverging', 'Diverging'), ('categorical', 'Categorical')], default='sequential', max_length=20)),
                ('center_value', models.FloatField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('time', timescale.db.models.fields.TimescaleDateTimeField(interval='1 day')),
                ('reference_time', models.DateTimeField(blank=True, db_index=True, help_text='When data was produced (model run time for forecasts)', null=True)),
                ('source_file', models.CharField(blank=True, help_text='Original source file path', max_length=500)),
                ('bounds', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, help_text='Bounding box [west, south, east, north]', null=True, size=4)),
                ('geometry', models.JSONField(blank=True, help_text='GeoJSON geometry for non-rectangular footprints', null=True)),
                ('width', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('resolution_x', models.FloatField(blank=True, null=True)),
                ('resolution_y', models.FloatField(blank=True, null=True)),
                ('crs', models.CharField(default='EPSG:4326', max_length=50)),
                ('properties', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-time'],
            },
        ),
        migrations.CreateModel(
            name='PaletteStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('value', models.FloatField(help_text='Numeric value at this stop (e.g. 11.5749)')),
                ('hex_value', models.CharField(help_text="Hex '#RRGGBB' or '#RRGGBBAA' (alpha optional)", max_length=9)),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Variable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('slug', models.SlugField(max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('transform_type', models.CharField(choices=[('passthrough', 'Passthrough (direct read)'), ('unit_convert', 'Unit Conversion'), ('vector_magnitude', 'Vector Magnitude (√(u² + v²))'), ('vector_direction', 'Vector Direction (atan2)'), ('band_math', 'Band Math (expression)'), ('rgb_composite', 'RGB Composite'), ('threshold', 'Threshold (mask)')], default='passthrough', max_length=30)),
                ('transform_expression', models.TextField(blank=True, help_text="For band_math: e.g., '(nir - red) / (nir + red)'")),
                ('unit_conversion', models.CharField(blank=True, choices=[('', 'None'), ('K_to_C', 'Kelvin to Celsius'), ('Pa_to_hPa', 'Pascal to hectoPascal'), ('m_to_mm', 'Meters to Millimeters'), ('ms_to_kmh', 'm/s to km/h'), ('kgm2s_to_mm', 'kg/m²/s to mm')], max_length=50)),
                ('units', models.CharField(blank=True, max_length=50)),
                ('value_min', models.FloatField()),
                ('value_max', models.FloatField()),
                ('scale_type', models.CharField(choices=[('linear', 'Linear'), ('log', 'Logarithmic'), ('sqrt', 'Square Root'), ('diverging', 'Diverging')], default='linear', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VariableSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('source_name', models.CharField(help_text="Name in source file, e.g., 'TMP_2maboveground', 'B04'", max_length=100)),
                ('vertical_dimension', models.CharField(blank=True, max_length=50)),
                ('vertical_value', models.FloatField(blank=True, null=True)),
                ('band_index', models.PositiveIntegerField(blank=True, null=True)),
                ('source_units', models.CharField(blank=True, max_length=50)),
                ('source_dtype', models.CharField(blank=True, max_length=20)),
                ('source_nodata', models.FloatField(blank=True, null=True)),
                ('role', models.CharField(default='primary', max_length=20)),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('provider', models.CharField(blank=True, max_length=255)),
                ('provider_url', models.URLField(blank=True)),
                ('license', models.CharField(blank=True, max_length=255)),
                ('file_format', models.CharField(choices=[('grib2', 'GRIB/GRIB2'), ('netcdf', 'NetCDF'), ('geotiff', 'GeoTIFF'), ('zarr', 'ZARR')], max_length=20)),
                ('archive_source_files', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('clip_mode', models.CharField(choices=[('none', 'No clipping'), ('bbox', 'Bounding box only'), ('mask', 'Precise geometry mask')], default='mask', help_text='How to apply boundary clipping', max_length=20)),
                ('boundary', models.ForeignKey(blank=True, help_text='Boundary to clip data to', null=True, on_delete=django.db.models.deletion.SET_NULL, to='adminboundarymanager.adminboundary')),
            ],
            options={
                'verbose_name_plural': 'Catalogs',
                'ordering': ['name'],
            },
        ),
    ]
