# Generated by Django 5.1.14 on 2025-12-04 14:03

import django.contrib.postgres.fields
import django_extensions.db.fields
import timescale.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('key', models.CharField(help_text="Unique key within item: 'visual', 'data', 'thumbnail', etc.", max_length=100)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('href', models.CharField(help_text='Storage path or URL to the asset', max_length=500)),
                ('media_type', models.CharField(help_text='MIME type', max_length=100)),
                ('file_size', models.BigIntegerField(blank=True, help_text='File size in bytes', null=True)),
                ('roles', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('data', 'Data'), ('visual', 'Visual'), ('thumbnail', 'Thumbnail'), ('overview', 'Overview'), ('metadata', 'Metadata')], max_length=20), default=list, size=None)),
                ('format', models.CharField(choices=[('cog', 'Cloud-Optimized GeoTIFF'), ('geotiff', 'GeoTIFF'), ('png', 'PNG'), ('webp', 'WebP'), ('jpeg', 'JPEG'), ('json', 'JSON')], max_length=20)),
                ('data_type', models.CharField(blank=True, choices=[('float32', 'Float32'), ('float16', 'Float16'), ('uint16', 'UInt16'), ('uint8', 'UInt8 (0-255)'), ('int16', 'Int16'), ('rgba', 'RGBA Color')], max_length=20, null=True)),
                ('width', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('bands', models.IntegerField(blank=True, default=1, null=True)),
                ('proj_epsg', models.IntegerField(blank=True, null=True)),
                ('proj_bbox', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, null=True, size=4)),
                ('extra_fields', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('provider', models.CharField(blank=True, help_text='Data provider, e.g., NOAA, UCSB, ECMWF', max_length=255)),
                ('provider_url', models.URLField(blank=True)),
                ('license', models.CharField(blank=True, max_length=255)),
                ('file_format', models.CharField(choices=[('grib', 'GRIB/GRIB2'), ('netcdf', 'NetCDF'), ('geotiff', 'GeoTIFF'), ('zarr', 'ZARR')], max_length=20)),
                ('archive_source_files', models.BooleanField(default=True, help_text='Whether to archive source files after processing')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ColorPalette',
            fields=[
                ('id', models.SlugField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('palette_type', models.CharField(choices=[('sequential', 'Sequential'), ('diverging', 'Diverging'), ('categorical', 'Categorical')], default='sequential', max_length=20)),
                ('colors', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=7), help_text="List of hex colors, e.g., ['#f7fbff', '#08306b']", size=None)),
                ('center_value', models.FloatField(blank=True, help_text='Center value for diverging palettes', null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('variable_type', models.CharField(choices=[('scalar', 'Scalar'), ('vector', 'Vector')], default='scalar', max_length=20)),
                ('primary_variable', models.CharField(max_length=100)),
                ('secondary_variable', models.CharField(blank=True, max_length=100)),
                ('vertical_dimension', models.CharField(blank=True, help_text="Name of vertical coordinate (e.g., 'isobaricInhPa', 'level', 'depth'). Leave empty for 2D/Surface data.", max_length=50)),
                ('vertical_value', models.FloatField(blank=True, help_text='Value to select (e.g., 850, 500, 10).', null=True)),
                ('source_units', models.CharField(blank=True, max_length=50)),
                ('units', models.CharField(blank=True, max_length=50)),
                ('unit_conversion', models.CharField(blank=True, choices=[('', 'None'), ('K_to_C', 'Kelvin to Celsius'), ('Pa_to_hPa', 'Pascal to hectoPascal'), ('m_to_mm', 'Meters to Millimeters'), ('ms_to_kmh', 'Meters/second to km/h'), ('kgm2s_to_mm', 'kg/m²/s to mm (precipitation rate)')], max_length=50)),
                ('value_min', models.FloatField(blank=True, null=True)),
                ('value_max', models.FloatField(blank=True, null=True)),
                ('scale_type', models.CharField(choices=[('linear', 'Linear'), ('log', 'Logarithmic'), ('sqrt', 'Square Root'), ('diverging', 'Diverging (centered on zero)')], default='linear', max_length=20)),
                ('bounds', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, null=True, size=4)),
                ('crs', models.CharField(default='EPSG:4326', max_length=50)),
                ('time_resolution', models.CharField(blank=True, choices=[('hourly', 'Hourly'), ('3hourly', '3-Hourly'), ('6hourly', '6-Hourly'), ('daily', 'Daily'), ('dekadal', 'Dekadal (10-day)'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], max_length=20)),
                ('time_start', models.DateTimeField(blank=True, editable=False, null=True)),
                ('time_end', models.DateTimeField(blank=True, editable=False, null=True)),
                ('item_count', models.PositiveIntegerField(default=0, editable=False)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('time', timescale.db.models.fields.TimescaleDateTimeField(interval='1 day')),
                ('run_time', models.DateTimeField(blank=True, help_text='Model run time for forecast data', null=True)),
                ('source_file', models.CharField(help_text='Original source file path', max_length=500)),
                ('bounds', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), help_text='Bounding box [minx, miny, maxx, maxy]', size=4)),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('resolution_x', models.FloatField(help_text='Pixel size in X direction')),
                ('resolution_y', models.FloatField(help_text='Pixel size in Y direction')),
                ('crs', models.CharField(default='EPSG:4326', max_length=50)),
                ('stats_min', models.FloatField(blank=True, null=True)),
                ('stats_max', models.FloatField(blank=True, null=True)),
                ('stats_mean', models.FloatField(blank=True, null=True)),
                ('stats_std', models.FloatField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-time'],
            },
        ),
    ]
