# Generated by Django 5.1.14 on 2025-12-04 14:03

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('georivacore', '0001_initial'),
        ('georivaloaders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='loader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='georivaloaders.loaderconfig'),
        ),
        migrations.AddField(
            model_name='dataset',
            name='collection',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='datasets', to='georivacore.collection'),
        ),
        migrations.AddField(
            model_name='dataset',
            name='palette',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='georivacore.colorpalette'),
        ),
        migrations.AddField(
            model_name='item',
            name='dataset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='georivacore.dataset'),
        ),
        migrations.AddField(
            model_name='asset',
            name='item',
            field=modelcluster.fields.ParentalKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='georivacore.item'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['dataset', 'time'], name='georivacore_dataset_4048a5_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['dataset', '-time'], name='georivacore_dataset_8a2495_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['run_time', 'time'], name='georivacore_run_tim_0983f4_idx'),
        ),
        migrations.AddConstraint(
            model_name='item',
            constraint=models.UniqueConstraint(fields=('time', 'dataset'), name='unique_time_per_dataset'),
        ),
        migrations.AddConstraint(
            model_name='item',
            constraint=models.UniqueConstraint(condition=models.Q(('run_time__isnull', False)), fields=('time', 'dataset', 'run_time'), name='unique_time_dataset_runtime'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['item', 'format'], name='georivacore_item_id_05dbec_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['item', 'key'], name='georivacore_item_id_c645c8_idx'),
        ),
        migrations.AddConstraint(
            model_name='asset',
            constraint=models.UniqueConstraint(fields=('item', 'key'), name='unique_asset_key_per_item'),
        ),
    ]
