# Generated by Django 5.1.14 on 2026-01-30 09:14

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('georivacore', '0001_initial'),
        ('georivasources', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalog',
            name='loader_profile',
            field=models.ForeignKey(blank=True, help_text='Loader profile to use for ingesting data for this catalog', null=True, on_delete=django.db.models.deletion.SET_NULL, to='georivasources.loaderprofile'),
        ),
        migrations.AddField(
            model_name='collection',
            name='catalog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collections', to='georivacore.catalog'),
        ),
        migrations.AddField(
            model_name='item',
            name='collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='georivacore.collection'),
        ),
        migrations.AddField(
            model_name='asset',
            name='item',
            field=modelcluster.fields.ParentalKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='georivacore.item'),
        ),
        migrations.AddField(
            model_name='palettestop',
            name='palette',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='georivacore.colorpalette'),
        ),
        migrations.AddField(
            model_name='variable',
            name='collection',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='variables', to='georivacore.collection'),
        ),
        migrations.AddField(
            model_name='variable',
            name='palette',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='georivacore.colorpalette'),
        ),
        migrations.AddField(
            model_name='asset',
            name='variable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='georivacore.variable'),
        ),
        migrations.AddField(
            model_name='variablesource',
            name='variable',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='georivacore.variable'),
        ),
        migrations.AlterUniqueTogether(
            name='collection',
            unique_together={('catalog', 'slug')},
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['collection', 'time'], name='georivacore_collect_b09451_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['collection', '-time'], name='georivacore_collect_866446_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['collection', 'reference_time', 'time'], name='georivacore_collect_cdbe06_idx'),
        ),
        migrations.AddConstraint(
            model_name='item',
            constraint=models.UniqueConstraint(condition=models.Q(('reference_time__isnull', True)), fields=('collection', 'time'), name='unique_time_per_collection'),
        ),
        migrations.AddConstraint(
            model_name='item',
            constraint=models.UniqueConstraint(condition=models.Q(('reference_time__isnull', False)), fields=('collection', 'time', 'reference_time'), name='unique_time_collection_reference'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['item'], name='georivacore_item_id_68ddcd_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['item', 'variable'], name='georivacore_item_id_1aac96_idx'),
        ),
        migrations.AddConstraint(
            model_name='asset',
            constraint=models.UniqueConstraint(fields=('item', 'variable', 'format'), name='unique_format_per_variable_per_item'),
        ),
    ]
