# Generated by Django 5.1.14 on 2026-04-08 15:37

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('georivacore', '0001_initial'),
        ('georivaingestion', '0001_initial'),
        ('georivasources', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='loader_profile',
            field=models.ForeignKey(blank=True, help_text='Loader profile to use for ingesting data for this catalog', null=True, on_delete=django.db.models.deletion.SET_NULL, to='georivasources.loaderprofile'),
        ),
        migrations.AddField(
            model_name='item',
            name='collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='georivacore.collection'),
        ),
        migrations.AddField(
            model_name='item',
            name='ingestion_log',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='georivaingestion.ingestionlog'),
        ),
        migrations.AddField(
            model_name='asset',
            name='item',
            field=modelcluster.fields.ParentalKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='georivacore.item'),
        ),
        migrations.AddField(
            model_name='palettestop',
            name='palette',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='georivacore.colorpalette'),
        ),
        migrations.AddField(
            model_name='catalog',
            name='topics',
            field=models.ManyToManyField(blank=True, help_text='Thematic topics for this catalog.', related_name='catalogs', to='georivacore.topic'),
        ),
        migrations.AddField(
            model_name='variable',
            name='collection',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='variables', to='georivacore.collection'),
        ),
        migrations.AddField(
            model_name='variable',
            name='palette',
            field=models.ForeignKey(blank=True, help_text="Color palette used for rendering PNG tiles and legend display. The palette's min/max stop values must exactly match this variable's value_min and value_max. If no palette is selected, a grayscale fallback is used.", null=True, on_delete=django.db.models.deletion.SET_NULL, to='georivacore.colorpalette'),
        ),
        migrations.AddField(
            model_name='variable',
            name='source_unit',
            field=models.ForeignKey(blank=True, help_text='Units of the raw data as it comes from the source file, e.g. Kelvin, Pa, m/s.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='georivacore.unit'),
        ),
        migrations.AddField(
            model_name='variable',
            name='unit',
            field=models.ForeignKey(help_text="Units of this variable's output after any conversion.", on_delete=django.db.models.deletion.PROTECT, related_name='+', to='georivacore.unit'),
        ),
        migrations.AddField(
            model_name='asset',
            name='variable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='georivacore.variable'),
        ),
        migrations.AlterUniqueTogether(
            name='collection',
            unique_together={('catalog', 'slug')},
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['collection', 'time'], name='georivacore_collect_b09451_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['collection', '-time'], name='georivacore_collect_866446_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['collection', 'reference_time', 'time'], name='georivacore_collect_cdbe06_idx'),
        ),
        migrations.AddConstraint(
            model_name='item',
            constraint=models.UniqueConstraint(condition=models.Q(('reference_time__isnull', True)), fields=('collection', 'time'), name='unique_time_per_collection'),
        ),
        migrations.AddConstraint(
            model_name='item',
            constraint=models.UniqueConstraint(condition=models.Q(('reference_time__isnull', False)), fields=('collection', 'time', 'reference_time'), name='unique_time_collection_reference'),
        ),
        migrations.AddIndex(
            model_name='variable',
            index=models.Index(fields=['slug', 'is_active'], name='variable_slug_active_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['item'], name='georivacore_item_id_68ddcd_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['item', 'variable'], name='georivacore_item_id_1aac96_idx'),
        ),
        migrations.AddConstraint(
            model_name='asset',
            constraint=models.UniqueConstraint(fields=('item', 'variable', 'format'), name='unique_format_per_variable_per_item'),
        ),
    ]
