# Generated by Django 5.1.14 on 2026-01-30 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('georivacore', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalog',
            name='file_format',
            field=models.CharField(choices=[('grib2', 'GRIB/GRIB2'), ('netcdf', 'NetCDF'), ('geotiff', 'GeoTIFF'), ('zarr', 'ZARR')], max_length=20),
        ),
    ]
