# Generated by Django 5.1.14 on 2026-01-07 09:55

import django.contrib.postgres.fields
import django.db.models.deletion
import django_extensions.db.fields
import modelcluster.fields
import timescale.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('georivacore', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('time', timescale.db.models.fields.TimescaleDateTimeField(interval='1 day')),
                ('reference_time', models.DateTimeField(blank=True, db_index=True, help_text='When data was produced (model run time for forecasts)', null=True)),
                ('source_file', models.CharField(blank=True, help_text='Original source file path', max_length=500)),
                ('bounds', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, help_text='Bounding box [west, south, east, north]', null=True, size=4)),
                ('geometry', models.JSONField(blank=True, help_text='GeoJSON geometry for non-rectangular footprints', null=True)),
                ('width', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('resolution_x', models.FloatField(blank=True, null=True)),
                ('resolution_y', models.FloatField(blank=True, null=True)),
                ('crs', models.CharField(default='EPSG:4326', max_length=50)),
                ('properties', models.JSONField(blank=True, default=dict)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='georivacore.collection')),
            ],
            options={
                'ordering': ['-time'],
            },
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('href', models.CharField(help_text='Storage path or URL', max_length=500)),
                ('media_type', models.CharField(blank=True, help_text='MIME type', max_length=100)),
                ('roles', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('data', 'Data'), ('visual', 'Visual'), ('thumbnail', 'Thumbnail'), ('overview', 'Overview'), ('metadata', 'Metadata')], max_length=20), default=list, size=None)),
                ('format', models.CharField(blank=True, choices=[('cog', 'Cloud-Optimized GeoTIFF'), ('zarr', 'Zarr'), ('geotiff', 'GeoTIFF'), ('png', 'PNG'), ('webp', 'WebP'), ('jpeg', 'JPEG'), ('json', 'JSON')], max_length=20)),
                ('file_size', models.BigIntegerField(blank=True, null=True)),
                ('checksum', models.CharField(blank=True, max_length=64)),
                ('width', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('bands', models.IntegerField(blank=True, default=1, null=True)),
                ('stats_min', models.FloatField(blank=True, null=True)),
                ('stats_max', models.FloatField(blank=True, null=True)),
                ('stats_mean', models.FloatField(blank=True, null=True)),
                ('stats_std', models.FloatField(blank=True, null=True)),
                ('extra_fields', models.JSONField(blank=True, default=dict)),
                ('variable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='georivacore.variable')),
                ('item', modelcluster.fields.ParentalKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='georivacore.item')),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['collection', 'time'], name='georivacore_collect_b09451_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['collection', '-time'], name='georivacore_collect_866446_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['collection', 'reference_time', 'time'], name='georivacore_collect_cdbe06_idx'),
        ),
        migrations.AddConstraint(
            model_name='item',
            constraint=models.UniqueConstraint(condition=models.Q(('reference_time__isnull', True)), fields=('collection', 'time'), name='unique_time_per_collection'),
        ),
        migrations.AddConstraint(
            model_name='item',
            constraint=models.UniqueConstraint(condition=models.Q(('reference_time__isnull', False)), fields=('collection', 'time', 'reference_time'), name='unique_time_collection_reference'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['item'], name='georivacore_item_id_68ddcd_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['item', 'variable'], name='georivacore_item_id_1aac96_idx'),
        ),
        migrations.AddConstraint(
            model_name='asset',
            constraint=models.UniqueConstraint(fields=('item', 'variable'), name='unique_variable_per_item'),
        ),
    ]
