# Generated by Django 5.2.11 on 2026-02-16 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('georivacore', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='variable',
            options={},
        ),
        migrations.AddIndex(
            model_name='variable',
            index=models.Index(fields=['slug', 'is_active'], name='variable_slug_active_idx'),
        ),
    ]
