# Generated by Django 6.0.6 on 2026-06-22 14:23

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('georivacore', '0003_add_default_units'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='format',
            field=models.CharField(blank=True, choices=[('cog', 'Cloud-Optimized GeoTIFF'), ('zarr', 'Zarr'), ('geotiff', 'GeoTIFF'), ('netcdf', 'NetCDF'), ('grib2', 'GRIB2'), ('png', 'PNG'), ('webp', 'WebP'), ('jpeg', 'JPEG'), ('json', 'JSON')], max_length=20),
        ),
        migrations.AlterField(
            model_name='asset',
            name='roles',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('data', 'Data'), ('visual', 'Visual'), ('thumbnail', 'Thumbnail'), ('overview', 'Overview'), ('metadata', 'Metadata'), ('source', 'Source')], max_length=20), default=list),
        ),
    ]
