# Generated by Django 5.1.14 on 2026-02-17 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('georivacore', '0003_alter_variable_options_and_more'),
        ('georivasources', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalog',
            name='loader_profile',
        ),
        migrations.AddField(
            model_name='collection',
            name='is_loader_active',
            field=models.BooleanField(default=True, help_text='Loader active status'),
        ),
        migrations.AddField(
            model_name='collection',
            name='loader_profile',
            field=models.ForeignKey(blank=True, help_text='Loader profile to use for ingesting data for this catalog', null=True, on_delete=django.db.models.deletion.SET_NULL, to='georivasources.loaderprofile'),
        ),
    ]
