# Generated by Django 5.1.14 on 2026-01-12 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('georivacore', '0003_item_asset_item_georivacore_collect_b09451_idx_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='asset',
            name='unique_variable_per_item',
        ),
        migrations.AddConstraint(
            model_name='asset',
            constraint=models.UniqueConstraint(fields=('item', 'variable', 'format'), name='unique_format_per_variable_per_item'),
        ),
    ]
