# Generated by Django 6.0.6 on 2026-06-23 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('georivacore', '0004_alter_asset_format_alter_asset_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('internal', 'Internal')], default='public', help_text='Public collections are served via STAC/EDR/pages/tiles. Internal collections are derivation intermediates — read by the engine as inputs but never served.', max_length=10),
        ),
    ]
