# Generated by Django 5.2.11 on 2026-03-09 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('georivacore', '0004_remove_catalog_loader_profile_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='colorpalette',
            options={'ordering': ['name'], 'verbose_name': 'Color Palette', 'verbose_name_plural': 'Color Palettes'},
        ),
    ]
