# Generated by Django 5.1.14 on 2026-01-15 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminboundarymanager', '0007_boundarymenupermission'),
        ('georivacore', '0004_remove_asset_unique_variable_per_item_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalog',
            name='boundary',
            field=models.ForeignKey(blank=True, help_text='Optional boundary to clip data to', null=True, on_delete=django.db.models.deletion.SET_NULL, to='adminboundarymanager.adminboundary'),
        ),
    ]
