# Generated by Django 5.2.13 on 2026-04-20 15:00

import django.contrib.postgres.fields
import georiva.core.models.collection
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('georivacore', '0004_add_default_units'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='boundary_stats_levels',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(choices=[(1, 'Level 1'), (2, 'Level 2'), (3, 'Level 3')]), blank=True, default=georiva.core.models.collection.default_adm_levels, help_text='Administrative boundary levels for zonal statistics. 1 = region, 2 = district, 3 = sub-district. Leave blank to disable. Stats are computed for all selected levels.', null=True, size=None),
        ),
    ]
