# Generated by Django 6.0.6 on 2026-07-08 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('georivacore', '0005_collection_visibility'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='variable',
            constraint=models.UniqueConstraint(fields=('collection', 'slug'), name='unique_variable_slug_per_collection'),
        ),
    ]
