# Generated by Django 5.1.14 on 2026-01-15 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminboundarymanager', '0007_boundarymenupermission'),
        ('georivacore', '0005_catalog_boundary'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalog',
            name='clip_mode',
            field=models.CharField(choices=[('none', 'No clipping'), ('bbox', 'Bounding box only'), ('mask', 'Precise geometry mask')], default='mask', help_text='How to apply boundary clipping', max_length=20),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='boundary',
            field=models.ForeignKey(blank=True, help_text='Boundary to clip data to', null=True, on_delete=django.db.models.deletion.SET_NULL, to='adminboundarymanager.adminboundary'),
        ),
    ]
