# Generated by Django 5.2.12 on 2026-03-11 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('georivacore', '0005_alter_colorpalette_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='is_loader_active',
        ),
    ]
