# Generated by Django 5.1.14 on 2026-01-15 15:58

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('georivacore', '0006_catalog_clip_mode_alter_catalog_boundary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colorpalette',
            name='colors',
        ),
        migrations.AlterField(
            model_name='colorpalette',
            name='center_value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='PaletteStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('value', models.FloatField(help_text='Numeric value at this stop (e.g. 11.5749)')),
                ('hex_value', models.CharField(help_text="Hex '#RRGGBB' or '#RRGGBBAA' (alpha optional)", max_length=9)),
                ('palette', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='georivacore.colorpalette')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
