# Generated by Django 5.1.14 on 2026-03-12 14:15

import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('georivacore', '0006_remove_collection_is_loader_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name', unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, help_text='Bootstrap Icons class e.g. bi-thermometer-half', max_length=50)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Topic',
                'verbose_name_plural': 'Topics',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='catalog',
            name='topics',
            field=models.ManyToManyField(blank=True, help_text='Thematic topics for this catalog.', related_name='catalogs', to='georivacore.topic'),
        ),
    ]
