# Generated by Django 6.0.6 on 2026-08-03 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('georivacore', '0007_data_managers_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('internal', 'Internal')], default='public', help_text='Public collections are served via STAC/EDR/pages/tiles to anyone. Private collections are served only to signed-in members of this organisation, over a session or an API key, and are invisible to everybody else. Internal collections are derivation intermediates — read by the engine as inputs but never served.', max_length=10),
        ),
    ]
