# Generated by Django 5.1.14 on 2026-01-15 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('georivacore', '0007_remove_colorpalette_colors_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colorpalette',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
