# Generated by Django 5.1.14 on 2026-01-27 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('georivacore', '0008_alter_colorpalette_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variable',
            name='value_max',
        ),
        migrations.RemoveField(
            model_name='variable',
            name='value_min',
        ),
    ]
