# Generated by Django 5.1.14 on 2026-01-28 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('georivacore', '0008_alter_colorpalette_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variable',
            name='value_max',
            field=models.FloatField(default=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='variable',
            name='value_min',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
