# Generated by Django 5.1.14 on 2026-03-12 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('georivacore', '0008_add_default_topics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='time_resolution',
            field=models.CharField(blank=True, choices=[('sub_hourly', 'Sub-Hourly'), ('hourly', 'Hourly'), ('3hourly', '3-Hourly'), ('6hourly', '6-Hourly'), ('12hourly', '12-Hourly'), ('daily', 'Daily'), ('pentadal', 'Pentadal'), ('dekadal', 'Dekadal'), ('monthly', 'Monthly'), ('sub_seasonal', 'Sub-Seasonal'), ('seasonal', 'Seasonal'), ('annual', 'Annual'), ('climatology', 'Climatology')], max_length=20),
        ),
    ]
