# Generated by Django 6.0.6 on 2026-08-03 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('georivacore', '0008_alter_collection_visibility'),
        ('organisations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='colorpalette',
            name='organisation',
            field=models.ForeignKey(blank=True, help_text='The organisation this palette belongs to. Left empty, it is part of the instance-wide palette library every organisation can use.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='color_palettes', to='organisations.organisation'),
        ),
        migrations.AddConstraint(
            model_name='colorpalette',
            constraint=models.UniqueConstraint(fields=('organisation', 'name'), name='unique_palette_name_per_organisation'),
        ),
        migrations.AddConstraint(
            model_name='colorpalette',
            constraint=models.UniqueConstraint(condition=models.Q(('organisation__isnull', True)), fields=('name',), name='unique_global_palette_name'),
        ),
    ]
