# Generated by Django 5.1.14 on 2026-03-16 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('georivacore', '0009_alter_collection_time_resolution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalog',
            name='archive_source_files',
            field=models.BooleanField(default=False, help_text='Should archive source files'),
        ),
    ]
