# Generated by Django 6.0.6 on 2026-08-07 17:03

import django.core.validators
import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('georivacore', '0009_colorpalette_organisation_and_more'),
        ('organisations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColorRamp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('ramp_type', models.CharField(choices=[('sequential', 'Sequential'), ('diverging', 'Diverging'), ('qualitative', 'Qualitative')], default='sequential', max_length=20)),
                ('organisation', models.ForeignKey(blank=True, help_text='The organisation this ramp belongs to. Left empty, it is part of the instance-wide ramp catalog every organisation can use.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='color_ramps', to='organisations.organisation')),
            ],
            options={
                'verbose_name': 'Color Ramp',
                'verbose_name_plural': 'Color Ramps',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ColorRampStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('hex_value', models.CharField(help_text="Hex '#RRGGBB' or '#RRGGBBAA' (alpha optional)", max_length=9, validators=[django.core.validators.RegexValidator(message="Enter a hex color such as '#RRGGBB' or '#RRGGBBAA'.", regex='^#?(?:[0-9a-fA-F]{3,4}|[0-9a-fA-F]{6}|[0-9a-fA-F]{8})$')])),
                ('position', models.FloatField(blank=True, help_text='Where along the ramp this color sits, 0–1. Left empty, colors are spread evenly.', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('ramp', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='georivacore.colorramp')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='colorramp',
            constraint=models.UniqueConstraint(fields=('organisation', 'name'), name='unique_ramp_name_per_organisation'),
        ),
        migrations.AddConstraint(
            model_name='colorramp',
            constraint=models.UniqueConstraint(condition=models.Q(('organisation__isnull', True)), fields=('name',), name='unique_global_ramp_name'),
        ),
    ]
