# Generated by Django 5.1.14 on 2026-01-28 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('georivacore', '0009_alter_variable_value_max_alter_variable_value_min'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalog',
            name='data_source',
        ),
    ]
