# Generated by Django 5.1.14 on 2026-01-28 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('georivacore', '0010_remove_catalog_data_source'),
        ('georivasources', '__first__'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalog',
            name='loader_profile',
            field=models.ForeignKey(blank=True, help_text='Loader profile to use for ingesting data for this catalog', null=True, on_delete=django.db.models.deletion.SET_NULL, to='georivasources.loaderprofile'),
        ),
    ]
