# Generated by Django 5.1.14 on 2026-03-16 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('georivacore', '0010_alter_catalog_archive_source_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='forecast_horizon_hours',
            field=models.PositiveIntegerField(blank=True, help_text='Max forecast horizon in hours (e.g. 240 for GFS)', null=True),
        ),
        migrations.AddField(
            model_name='collection',
            name='is_forecast',
            field=models.BooleanField(default=False, help_text='True if items represent forecast (future) data with a reference_time'),
        ),
        migrations.AddField(
            model_name='collection',
            name='retain_latest_run_only',
            field=models.BooleanField(default=False, help_text='If True, only keep items from the most recent reference_time run.'),
        ),
        migrations.AddField(
            model_name='collection',
            name='retain_past_forecasts',
            field=models.BooleanField(default=False, help_text='If True, keep items whose valid_time is in the past. If False, a cleanup task prunes them.'),
        ),
    ]
