# Generated by Django 6.0.6 on 2026-08-07 17:50

import django.core.validators
import django.db.models.deletion
import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('georivacore', '0011_seed_color_ramp_catalog'),
    ]

    operations = [
        migrations.CreateModel(
            name='VariableStyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(help_text='URL-safe identifier for this style, used to select it on tile and config URLs. Unique within the variable.', max_length=255)),
                ('is_default', models.BooleanField(default=False, help_text='The style served when no style is asked for by name.')),
                ('mode', models.CharField(choices=[('continuous', 'Continuous gradient'), ('stepped', 'Stepped classes')], default='continuous', max_length=20)),
                ('steps', models.PositiveSmallIntegerField(blank=True, help_text='Number of classes for stepped mode.', null=True, validators=[django.core.validators.MinValueValidator(2)])),
                ('stops', models.JSONField(blank=True, default=list)),
                ('ramp', models.ForeignKey(blank=True, help_text='The ramp this style was generated from — lineage and re-apply only; the stops below are what actually renders.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='georivacore.colorramp')),
                ('variable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='styles', to='georivacore.variable')),
            ],
            options={
                'verbose_name': 'Variable Style',
                'verbose_name_plural': 'Variable Styles',
                'ordering': ['-is_default', 'name'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('variable',), name='unique_default_style_per_variable'), models.UniqueConstraint(fields=('variable', 'slug'), name='unique_style_slug_per_variable')],
            },
        ),
    ]
