# Generated by Django 5.2.12 on 2026-03-31 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('georivacore', '0011_collection_forecast_horizon_hours_and_more'),
        ('georivaingestion', '0002_ingestionlog_force_reingest'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='ingestion_log',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='georivaingestion.ingestionlog'),
        ),
    ]
