# Generated by Django 6.0.6 on 2026-08-07 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('georivacore', '0013_migrate_palettes_to_styles'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='colorpalette',
            name='unique_palette_name_per_organisation',
        ),
        migrations.RemoveConstraint(
            model_name='colorpalette',
            name='unique_global_palette_name',
        ),
        migrations.RemoveField(
            model_name='variable',
            name='palette',
        ),
        migrations.AlterField(
            model_name='variable',
            name='value_max',
            field=models.FloatField(help_text="Maximum expected data value in the variable's output units. Used for color mapping, COG encoding range, and legend display. Values above this will be clipped to the style's maximum color."),
        ),
        migrations.AlterField(
            model_name='variable',
            name='value_min',
            field=models.FloatField(help_text="Minimum expected data value in the variable's output units. Used for color mapping, COG encoding range, and legend display. Values below this will be clipped to the style's minimum color."),
        ),
        migrations.RemoveField(
            model_name='colorpalette',
            name='organisation',
        ),
        migrations.DeleteModel(
            name='PaletteStop',
        ),
        migrations.DeleteModel(
            name='ColorPalette',
        ),
    ]
