# Generated by Django 5.1.14 on 2026-06-09 10:02

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('georivacore', '0001_initial'),
        ('task_ferry', '0002_add_ingestion_job'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataArrivalJob',
            fields=[
                ('job_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='task_ferry.job')),
                ('files_total', models.IntegerField(default=0)),
                ('files_fetched', models.IntegerField(default=0)),
                ('files_skipped', models.IntegerField(default=0)),
                ('files_failed', models.IntegerField(default=0)),
                ('bytes_transferred', models.BigIntegerField(default=0)),
            ],
            bases=('task_ferry.job',),
        ),
        migrations.CreateModel(
            name='FileIngestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bucket', models.CharField(help_text="Origin bucket type: 'incoming' or 'sources'", max_length=50)),
                ('file_path', models.CharField(help_text='Path relative to bucket root: {catalog}/{collection}/{filename}', max_length=500)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('locked_by', models.CharField(blank=True, default='', help_text='Worker ID that holds the lock', max_length=100)),
                ('retry_count', models.IntegerField(default=0)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('archive_path', models.CharField(blank=True, default='', max_length=500)),
                ('items_created', models.IntegerField(default=0)),
                ('assets_created', models.IntegerField(default=0)),
                ('error', models.TextField(blank=True, default='')),
                ('catalog_slug', models.CharField(blank=True, default='', max_length=100)),
                ('collection_slug', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('reference_time', models.DateTimeField(blank=True, null=True)),
                ('file_size', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('force_reingest', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FileIngestionJob',
            fields=[
                ('job_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='task_ferry.job')),
                ('file_path', models.CharField(help_text='Path relative to bucket root.', max_length=500)),
                ('bucket', models.CharField(help_text="Origin bucket: 'incoming' or 'sources'.", max_length=50)),
                ('items_created', models.IntegerField(default=0)),
                ('assets_created', models.IntegerField(default=0)),
            ],
            bases=('task_ferry.job',),
        ),
        migrations.CreateModel(
            name='DataArrival',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger', models.CharField(choices=[('scheduled', 'Scheduled'), ('manual_upload', 'Manual Upload')], max_length=20)),
                ('status', models.CharField(choices=[('uploading', 'Uploading'), ('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('partial', 'Partial'), ('failed', 'Failed'), ('empty', 'Empty')], default='pending', max_length=20)),
                ('file_path', models.CharField(blank=True, default='', max_length=500)),
                ('files_requested', models.IntegerField(default=0)),
                ('files_fetched', models.IntegerField(default=0)),
                ('files_skipped', models.IntegerField(default=0)),
                ('files_failed', models.IntegerField(default=0)),
                ('files_queued', models.IntegerField(default=0)),
                ('bytes_transferred', models.BigIntegerField(default=0)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('collection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='data_arrivals', to='georivacore.collection')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
