# Generated by Django 6.0.6 on 2026-06-15 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('georivacore', '0001_initial'),
        ('task_ferry', '0002_add_ingestion_job'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManualUploadConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_forecast', models.BooleanField(default=False)),
                ('valid_time_format', models.CharField(choices=[('YYYYMMDD', 'YYYYMMDD'), ('DDMMYYYY', 'DDMMYYYY'), ('YYYYMMDDHH', 'YYYYMMDDHH'), ('YYYYMMDDHHMM', 'YYYYMMDDHHMM'), ('DDMMYY', 'DDMMYY'), ('YYMMDD', 'YYMMDD'), ('CONTENT', 'From file content')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ManualUploadConfigVariable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variable_name', models.CharField(max_length=255)),
                ('long_name', models.CharField(blank=True, default='', max_length=255)),
                ('units', models.CharField(blank=True, default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_filename', models.CharField(max_length=500)),
                ('file_path', models.CharField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('uploading', 'Uploading'), ('stored', 'Stored'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error', models.TextField(blank=True)),
                ('bytes', models.BigIntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='UploadSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='FileIngestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bucket', models.CharField(help_text="Origin bucket type: 'incoming' or 'sources'", max_length=50)),
                ('file_path', models.CharField(help_text='Path relative to bucket root: {catalog}/{collection}/{filename}', max_length=500)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('locked_by', models.CharField(blank=True, default='', help_text='Worker ID that holds the lock', max_length=100)),
                ('retry_count', models.IntegerField(default=0)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('archive_path', models.CharField(blank=True, default='', max_length=500)),
                ('items_created', models.IntegerField(default=0)),
                ('assets_created', models.IntegerField(default=0)),
                ('error', models.TextField(blank=True, default='')),
                ('reference_time', models.DateTimeField(blank=True, null=True)),
                ('file_size', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('force_reingest', models.BooleanField(default=False)),
                ('variables_discovered', models.IntegerField(null=True)),
                ('valid_time_start', models.DateTimeField(null=True)),
                ('valid_time_end', models.DateTimeField(null=True)),
                ('timestep_count', models.IntegerField(null=True)),
                ('collections', models.ManyToManyField(blank=True, related_name='file_ingestions', to='georivacore.collection')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FileIngestionJob',
            fields=[
                ('job_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='task_ferry.job')),
                ('file_path', models.CharField(help_text='Path relative to bucket root.', max_length=500)),
                ('bucket', models.CharField(help_text="Origin bucket: 'incoming' or 'sources'.", max_length=50)),
                ('items_created', models.IntegerField(default=0)),
                ('assets_created', models.IntegerField(default=0)),
                ('file_ingestion', models.ForeignKey(blank=True, help_text='Lock record for this file; set after the lock is acquired.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='georivaingestion.fileingestion')),
            ],
            bases=('task_ferry.job',),
        ),
        migrations.CreateModel(
            name='LoaderJob',
            fields=[
                ('job_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='task_ferry.job')),
                ('files_total', models.IntegerField(default=0)),
                ('files_fetched', models.IntegerField(default=0)),
                ('files_skipped', models.IntegerField(default=0)),
                ('files_failed', models.IntegerField(default=0)),
                ('bytes_transferred', models.BigIntegerField(default=0)),
                ('collection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loader_jobs', to='georivacore.collection')),
            ],
            bases=('task_ferry.job',),
        ),
    ]
