# Generated by Django 5.1.14 on 2026-04-08 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IngestionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bucket', models.CharField(help_text="Origin bucket type: 'incoming' or 'sources'", max_length=50)),
                ('file_path', models.CharField(help_text='Path relative to bucket root: {catalog}/{collection}/{filename}', max_length=500)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('locked_by', models.CharField(blank=True, default='', help_text='Worker ID that holds the lock', max_length=100)),
                ('retry_count', models.IntegerField(default=0)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('archive_path', models.CharField(blank=True, default='', max_length=500)),
                ('items_created', models.IntegerField(default=0)),
                ('assets_created', models.IntegerField(default=0)),
                ('error', models.TextField(blank=True, default='')),
                ('catalog_slug', models.CharField(blank=True, default='', max_length=100)),
                ('collection_slug', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('reference_time', models.DateTimeField(blank=True, null=True)),
                ('file_size', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('force_reingest', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
