# Generated by Django 5.1.14 on 2026-04-08 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('georivaingestion', '0001_initial'),
        ('georivasources', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingestionlog',
            name='loader_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingestion_logs', to='georivasources.loaderrun'),
        ),
        migrations.AddIndex(
            model_name='ingestionlog',
            index=models.Index(fields=['status', 'created_at'], name='idx_ingestion_status_created'),
        ),
        migrations.AddIndex(
            model_name='ingestionlog',
            index=models.Index(fields=['status', 'locked_at'], name='idx_ingestion_status_locked'),
        ),
        migrations.AddIndex(
            model_name='ingestionlog',
            index=models.Index(fields=['bucket', 'status'], name='idx_ingestion_bucket_status'),
        ),
        migrations.AlterUniqueTogether(
            name='ingestionlog',
            unique_together={('bucket', 'file_path')},
        ),
    ]
