# Generated by Django 6.0.6 on 2026-06-15 10:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('georivacore', '0001_initial'),
        ('georivaingestion', '0001_initial'),
        ('georivasources', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='loaderjob',
            name='data_feed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loader_jobs', to='georivasources.datafeed'),
        ),
        migrations.AddField(
            model_name='manualuploadconfig',
            name='catalog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manual_upload_configs', to='georivacore.catalog'),
        ),
        migrations.AddField(
            model_name='manualuploadconfigvariable',
            name='collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manual_upload_variables', to='georivacore.collection'),
        ),
        migrations.AddField(
            model_name='manualuploadconfigvariable',
            name='config',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variables', to='georivaingestion.manualuploadconfig'),
        ),
        migrations.AddField(
            model_name='uploadsession',
            name='catalog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upload_sessions', to='georivacore.catalog'),
        ),
        migrations.AddField(
            model_name='uploadsession',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='upload_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_files', to='georivaingestion.uploadsession'),
        ),
        migrations.AddIndex(
            model_name='fileingestion',
            index=models.Index(fields=['status', 'created_at'], name='idx_ingestion_status_created'),
        ),
        migrations.AddIndex(
            model_name='fileingestion',
            index=models.Index(fields=['status', 'locked_at'], name='idx_ingestion_status_locked'),
        ),
        migrations.AddIndex(
            model_name='fileingestion',
            index=models.Index(fields=['bucket', 'status'], name='idx_ingestion_bucket_status'),
        ),
        migrations.AlterUniqueTogether(
            name='fileingestion',
            unique_together={('bucket', 'file_path')},
        ),
        migrations.AddConstraint(
            model_name='manualuploadconfig',
            constraint=models.UniqueConstraint(fields=('catalog', 'name'), name='unique_manual_upload_config_name_per_catalog'),
        ),
        migrations.AlterUniqueTogether(
            name='manualuploadconfigvariable',
            unique_together={('config', 'variable_name')},
        ),
    ]
