# Generated by Django 5.1.14 on 2026-03-17 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('georivaingestion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingestionlog',
            name='force_reingest',
            field=models.BooleanField(default=False),
        ),
    ]
