# Generated by Django 5.1.14 on 2026-06-09 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('georivacore', '0001_initial'),
        ('georivaingestion', '0001_initial'),
        ('georivasources', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataarrival',
            name='data_feed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='arrivals', to='georivasources.datafeed'),
        ),
        migrations.AddField(
            model_name='dataarrivaljob',
            name='collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='data_arrival_jobs', to='georivacore.collection'),
        ),
        migrations.AddField(
            model_name='dataarrivaljob',
            name='data_arrival',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='georivaingestion.dataarrival'),
        ),
        migrations.AddField(
            model_name='dataarrivaljob',
            name='data_feed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='arrival_jobs', to='georivasources.datafeed'),
        ),
        migrations.AddField(
            model_name='fileingestion',
            name='data_arrival',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_ingestions', to='georivaingestion.dataarrival'),
        ),
        migrations.AddField(
            model_name='fileingestion',
            name='item',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='file_ingestions', to='georivacore.item'),
        ),
        migrations.AddField(
            model_name='fileingestionjob',
            name='file_ingestion',
            field=models.OneToOneField(blank=True, help_text='Lock record for this file; set after the lock is acquired.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job', to='georivaingestion.fileingestion'),
        ),
        migrations.AddIndex(
            model_name='fileingestion',
            index=models.Index(fields=['status', 'created_at'], name='idx_ingestion_status_created'),
        ),
        migrations.AddIndex(
            model_name='fileingestion',
            index=models.Index(fields=['status', 'locked_at'], name='idx_ingestion_status_locked'),
        ),
        migrations.AddIndex(
            model_name='fileingestion',
            index=models.Index(fields=['bucket', 'status'], name='idx_ingestion_bucket_status'),
        ),
        migrations.AlterUniqueTogether(
            name='fileingestion',
            unique_together={('bucket', 'file_path')},
        ),
    ]
