# Generated by Django 5.2.12 on 2026-03-31 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('georivaingestion', '0002_ingestionlog_force_reingest'),
        ('georivasources', '0004_remove_loaderprofile_data_source_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingestionlog',
            name='loader_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingestion_logs', to='georivasources.loaderrun'),
        ),
    ]
