# Generated by Django 5.1.14 on 2026-05-28 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('georivaingestion', '0002_initial'),
        ('task_ferry', '0002_add_ingestion_job'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngestionJob',
            fields=[
                ('job_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='task_ferry.job')),
                ('file_path', models.CharField(help_text='Path relative to bucket root.', max_length=500)),
                ('bucket', models.CharField(help_text="Origin bucket: 'incoming' or 'sources'.", max_length=50)),
                ('items_created', models.IntegerField(default=0)),
                ('assets_created', models.IntegerField(default=0)),
                ('ingestion_log', models.OneToOneField(blank=True, help_text='Lock record for this file; set after the lock is acquired.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job', to='georivaingestion.ingestionlog')),
            ],
            bases=('task_ferry.job',),
        ),
    ]
