# Generated by Django 5.1.14 on 2026-06-08 16:57

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('georivacore', '0003_add_default_units'),
        ('georivaingestion', '0002_initial'),
        ('georivasources', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataArrival',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger', models.CharField(choices=[('scheduled', 'Scheduled'), ('manual_upload', 'Manual Upload')], max_length=20)),
                ('status', models.CharField(choices=[('uploading', 'Uploading'), ('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('partial', 'Partial'), ('failed', 'Failed'), ('empty', 'Empty')], default='pending', max_length=20)),
                ('file_path', models.CharField(blank=True, default='', max_length=500)),
                ('files_requested', models.IntegerField(default=0)),
                ('files_fetched', models.IntegerField(default=0)),
                ('files_skipped', models.IntegerField(default=0)),
                ('files_failed', models.IntegerField(default=0)),
                ('files_queued', models.IntegerField(default=0)),
                ('bytes_transferred', models.BigIntegerField(default=0)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('collection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='data_arrivals', to='georivacore.collection')),
                ('data_feed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='arrivals', to='georivasources.datafeed')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
