# Generated by Django 5.2.15 on 2026-06-09 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('georivaingestion', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataarrival',
            name='error_message',
            field=models.TextField(blank=True, default=''),
        ),
    ]
