# Generated by Django 6.0.6 on 2026-08-06 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('georivaingestion', '0002_initial'),
        ('georivasources', '0010_fetchrun_resumed_from_alter_fetchrun_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='loaderjob',
            name='resume_of_run',
            field=models.ForeignKey(blank=True, help_text='Set on jobs the stale-run sweep enqueued to resume an interrupted FetchRun; threads resume lineage to the new run.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resume_jobs', to='georivasources.fetchrun'),
        ),
    ]
