# Generated by Django 5.2.15 on 2026-06-09 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('georivacore', '0003_add_default_units'),
        ('georivaingestion', '0003_dataarrival_error_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManualUploadConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_forecast', models.BooleanField(default=False)),
                ('valid_time_format', models.CharField(choices=[('YYYYMMDD', 'YYYYMMDD'), ('DDMMYYYY', 'DDMMYYYY'), ('YYYYMMDDHH', 'YYYYMMDDHH'), ('YYYYMMDDHHMM', 'YYYYMMDDHHMM'), ('DDMMYY', 'DDMMYY'), ('YYMMDD', 'YYMMDD')], max_length=20)),
                ('catalog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manual_upload_configs', to='georivacore.catalog')),
            ],
        ),
        migrations.CreateModel(
            name='ManualUploadConfigVariable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variable_name', models.CharField(max_length=255)),
                ('long_name', models.CharField(blank=True, default='', max_length=255)),
                ('units', models.CharField(blank=True, default='', max_length=50)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manual_upload_variables', to='georivacore.collection')),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variables', to='georivaingestion.manualuploadconfig')),
            ],
            options={
                'unique_together': {('config', 'variable_name')},
            },
        ),
    ]
