# Generated by Django 6.0.6 on 2026-09-08 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('georivacore', '0015_alter_variable_value_max_alter_variable_value_min'),
        ('georivaingestion', '0003_loaderjob_resume_of_run'),
    ]

    operations = [
        migrations.CreateModel(
            name='RunIngestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_time', models.DateTimeField(help_text='The model run this row tracks. Never null: a collection without reference times has no run boundary to track.')),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], db_index=True, default='open', max_length=20)),
                ('revision', models.PositiveIntegerField(default=0, help_text='Bumped every time a closed run reopens. Monotonic per row.')),
                ('closed_by', models.CharField(blank=True, choices=[('declared_set', 'Declared expected set'), ('upload_session', 'Upload session completed'), ('quiet_period', 'Quiet period'), ('manual', 'Closed by an operator')], default='', max_length=20)),
                ('file_count', models.IntegerField(default=0, help_text='Distinct files that have completed into this collection for this reference time.')),
                ('expected_file_count', models.IntegerField(blank=True, help_text='Size of the declared expected set, when the arrival route declares one. Null on routes that cannot.', null=True)),
                ('last_file_at', models.DateTimeField(blank=True, help_text='When the most recent file completed into this run. The clock the quiet-period closer reads.', null=True)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='run_ingestions', to='georivacore.collection')),
            ],
            options={
                'verbose_name': 'Run ingestion',
                'ordering': ['-reference_time'],
                'indexes': [models.Index(fields=['status', 'last_file_at'], name='idx_runingestion_status_last'), models.Index(fields=['collection', '-reference_time'], name='idx_runingestion_col_reftime')],
                'unique_together': {('collection', 'reference_time')},
            },
        ),
    ]
