# Generated by Django 5.2.15 on 2026-06-09 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('georivaingestion', '0004_manualuploadconfig_manualuploadconfigvariable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manualuploadconfig',
            name='valid_time_format',
            field=models.CharField(choices=[('YYYYMMDD', 'YYYYMMDD'), ('DDMMYYYY', 'DDMMYYYY'), ('YYYYMMDDHH', 'YYYYMMDDHH'), ('YYYYMMDDHHMM', 'YYYYMMDDHHMM'), ('DDMMYY', 'DDMMYY'), ('YYMMDD', 'YYMMDD'), ('CONTENT', 'From file content')], max_length=20),
        ),
    ]
