# Generated by Django 5.2.15 on 2026-06-12 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('georivaingestion', '0010_uploadsession_uploadedfile_fileingestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileingestion',
            name='timestep_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='fileingestion',
            name='valid_time_end',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='fileingestion',
            name='valid_time_start',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='fileingestion',
            name='variables_discovered',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='fileingestion',
            name='data_arrival',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='file_ingestions', to='georivaingestion.dataarrival'),
        ),
    ]
