# Generated by Django 5.2.15 on 2026-06-12 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('georivacore', '0004_item_source_file_index'),
        ('georivaingestion', '0011_fileingestion_nullable_arrival_summary_fields'),
        ('georivasources', '0002_fetchrun_fetchedfile'),
        ('task_ferry', '0002_add_ingestion_job'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataarrivaljob',
            name='data_arrival',
        ),
        migrations.RemoveField(
            model_name='fileingestion',
            name='data_arrival',
        ),
        migrations.RemoveField(
            model_name='dataarrivaljob',
            name='collection',
        ),
        migrations.RemoveField(
            model_name='dataarrivaljob',
            name='data_feed',
        ),
        migrations.RemoveField(
            model_name='dataarrivaljob',
            name='job_ptr',
        ),
        migrations.CreateModel(
            name='LoaderJob',
            fields=[
                ('job_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='task_ferry.job')),
                ('files_total', models.IntegerField(default=0)),
                ('files_fetched', models.IntegerField(default=0)),
                ('files_skipped', models.IntegerField(default=0)),
                ('files_failed', models.IntegerField(default=0)),
                ('bytes_transferred', models.BigIntegerField(default=0)),
                ('collection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loader_jobs', to='georivacore.collection')),
                ('data_feed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loader_jobs', to='georivasources.datafeed')),
            ],
            bases=('task_ferry.job',),
        ),
        migrations.DeleteModel(
            name='DataArrival',
        ),
        migrations.DeleteModel(
            name='DataArrivalJob',
        ),
    ]
