# Generated by Django 6.0.6 on 2026-06-22 14:45

import django.contrib.postgres.fields
import django.db.models.deletion
import django_extensions.db.fields
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('georivacore', '0004_alter_asset_format_alter_asset_roles'),
    ]

    operations = [
        migrations.CreateModel(
            name='StagingCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('slug', models.SlugField(max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('bounds', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, null=True, size=4)),
                ('crs', models.CharField(default='EPSG:4326', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('catalog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staging_collections', to='georivacore.catalog')),
            ],
            options={
                'ordering': ['catalog', 'name'],
                'unique_together': {('catalog', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='StagingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('source_file', models.CharField(blank=True, db_index=True, help_text='Original source file path', max_length=500)),
                ('bounds', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, help_text='Bounding box [west, south, east, north]', null=True, size=4)),
                ('geometry', models.JSONField(blank=True, help_text='GeoJSON geometry for non-rectangular footprints', null=True)),
                ('width', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('resolution_x', models.FloatField(blank=True, null=True)),
                ('resolution_y', models.FloatField(blank=True, null=True)),
                ('crs', models.CharField(default='EPSG:4326', max_length=50)),
                ('properties', models.JSONField(blank=True, default=dict)),
                ('datetime', models.DateTimeField(blank=True, db_index=True, help_text='Single valid time, when the file represents one slice', null=True)),
                ('start_datetime', models.DateTimeField(blank=True, db_index=True, help_text='Start of the temporal extent for a multi-temporal file', null=True)),
                ('end_datetime', models.DateTimeField(blank=True, db_index=True, help_text='End of the temporal extent for a multi-temporal file', null=True)),
                ('reference_time', models.DateTimeField(blank=True, db_index=True, help_text='Model run time, for forecast inputs', null=True)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='georivastaging.stagingcollection')),
            ],
            options={
                'ordering': ['collection', '-start_datetime', '-datetime'],
            },
        ),
        migrations.CreateModel(
            name='StagingAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('href', models.CharField(help_text='Storage path or URL', max_length=500)),
                ('media_type', models.CharField(blank=True, help_text='MIME type', max_length=100)),
                ('roles', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('data', 'Data'), ('visual', 'Visual'), ('thumbnail', 'Thumbnail'), ('overview', 'Overview'), ('metadata', 'Metadata'), ('source', 'Source')], max_length=20), default=list)),
                ('format', models.CharField(blank=True, choices=[('cog', 'Cloud-Optimized GeoTIFF'), ('zarr', 'Zarr'), ('geotiff', 'GeoTIFF'), ('netcdf', 'NetCDF'), ('grib2', 'GRIB2'), ('png', 'PNG'), ('webp', 'WebP'), ('jpeg', 'JPEG'), ('json', 'JSON')], max_length=20)),
                ('file_size', models.BigIntegerField(blank=True, null=True)),
                ('checksum', models.CharField(blank=True, max_length=64)),
                ('width', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('bands', models.IntegerField(blank=True, default=1, null=True)),
                ('stats_min', models.FloatField(blank=True, null=True)),
                ('stats_max', models.FloatField(blank=True, null=True)),
                ('stats_mean', models.FloatField(blank=True, null=True)),
                ('stats_std', models.FloatField(blank=True, null=True)),
                ('extra_fields', models.JSONField(blank=True, default=dict)),
                ('variable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staging_assets', to='georivacore.variable')),
                ('item', modelcluster.fields.ParentalKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='georivastaging.stagingitem')),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.AddIndex(
            model_name='stagingitem',
            index=models.Index(fields=['collection', 'start_datetime'], name='georivastag_collect_5760f8_idx'),
        ),
        migrations.AddIndex(
            model_name='stagingitem',
            index=models.Index(fields=['collection', 'datetime'], name='georivastag_collect_aa193a_idx'),
        ),
        migrations.AddIndex(
            model_name='stagingasset',
            index=models.Index(fields=['item'], name='georivastag_item_id_c9c290_idx'),
        ),
    ]
