# Generated by Django 6.0.6 on 2026-06-22 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('georivacore', '0004_alter_asset_format_alter_asset_roles'),
        ('georivastaging', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DerivationLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_id', models.CharField(max_length=100)),
                ('recipe_version', models.CharField(max_length=50)),
                ('input_hash', models.CharField(max_length=64)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('derived_item', models.ForeignKey(db_constraint=False, help_text='The Published item this lineage edge describes', on_delete=django.db.models.deletion.CASCADE, related_name='derivation_links', to='georivacore.item')),
                ('source_published_item', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='derived_into', to='georivacore.item')),
                ('source_staging_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='derived_into', to='georivastaging.stagingitem')),
            ],
            options={
                'indexes': [models.Index(fields=['derived_item'], name='georivastag_derived_f1d71e_idx'), models.Index(fields=['source_staging_item'], name='georivastag_source__75a51e_idx'), models.Index(fields=['source_published_item'], name='georivastag_source__8db4f4_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('source_published_item__isnull', True), ('source_staging_item__isnull', False)), models.Q(('source_published_item__isnull', False), ('source_staging_item__isnull', True)), _connector='OR'), name='derivationlink_exactly_one_source')],
            },
        ),
    ]
