# Generated by Django 6.0.6 on 2026-07-07 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('georivacore', '0005_collection_visibility'),
        ('georivastaging', '0002_derivationlink'),
    ]

    operations = [
        migrations.AddField(
            model_name='stagingcollection',
            name='collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staging_collections', to='georivacore.collection'),
        ),
    ]
