# Generated by Django 5.1.14 on 2025-12-04 14:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_public', models.BooleanField(default=False)),
                ('is_live', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('node_type', models.CharField(choices=[('source', 'Data Source'), ('transform', 'Transform'), ('temporal', 'Temporal Operation'), ('spatial', 'Spatial Operation'), ('filter', 'Filter/Mask'), ('output', 'Output')], max_length=20)),
                ('config', models.JSONField(default=dict)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='georivaanalysis.analysis')),
            ],
        ),
        migrations.CreateModel(
            name='Edge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_name', models.CharField(default='data', max_length=100)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edges', to='georivaanalysis.analysis')),
                ('source_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_edges', to='georivaanalysis.node')),
                ('target_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_edges', to='georivaanalysis.node')),
            ],
        ),
        migrations.AddConstraint(
            model_name='node',
            constraint=models.UniqueConstraint(fields=('analysis', 'name'), name='unique_node_name_per_analysis'),
        ),
        migrations.AddConstraint(
            model_name='edge',
            constraint=models.UniqueConstraint(fields=('target_node', 'input_name'), name='unique_input_per_node'),
        ),
    ]
