# Generated by Django 5.1.14 on 2026-04-20 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('georivaanalysis', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='node',
            name='analysis',
        ),
        migrations.RemoveField(
            model_name='edge',
            name='analysis',
        ),
        migrations.RemoveField(
            model_name='edge',
            name='source_node',
        ),
        migrations.RemoveField(
            model_name='edge',
            name='target_node',
        ),
        migrations.DeleteModel(
            name='Analysis',
        ),
        migrations.DeleteModel(
            name='Edge',
        ),
        migrations.DeleteModel(
            name='Node',
        ),
    ]
